### ISSUE TITLE
LMFDB map

### ISSUE THREAD

**Issue by alinabucur** [LMFDB/lmfdb#442] opened 2015-10-27 18:41 UTC
Make picture with javascript functionality.

**Comment by davidfarmer** [comment] 2015-10-28 16:45
Alina is working on this

**Comment by jvoight** [comment] 2015-11-07 16:15
Alina also says: I need (supershort, but informative) descriptions and examples for all the elements in there.  Alina, do you want to create a file where we can edit them in parallel, or do you want to just receive them by e-mail?

**Comment by jvoight** [comment] 2016-05-01 18:38
Closed as duplicate of #575.

**Closed by jvoight** 2016-05-01 18:38 UTC
Labels: April, critical, intro
