### ISSUE TITLE
Some elliptic curves over number fields crash when computing plots

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#1206] opened 2016-05-06 20:27 UTC
EllipticCurve/3.3.1016.1/9.2/b/3
causes
raise RuntimeError("No horizontal tangent lines on bounded component")
from line 74 in WebEllipticCurve.py in function EC_nf_plot

(I found this in the server log /home/lmfdb/lmfdb-git-prod/flasklog)

**Comment by AndrewVSutherland** [comment] 2016-05-07 09:37
@nmascot are you working on this?  If not I will look at it.

**Comment by AndrewVSutherland** [comment] 2016-05-07 14:06
The problem is due to sage raising the error "No horizontal tangent lines on bounded component" in the call to e.plot in the function EC_nf_plot in line 74 of WebEllipticCurve.py.  I will add a try except to work around this (so this curve will not have a plot)

**Comment by JohnCremona** [comment] 2016-05-07 14:23
@roed314 you wrote that error message -- can you help?

**Comment by AndrewVSutherland** [comment] 2016-05-07 14:39
@JohnCremona I just issued pull request #1218 to add a try/except to prevent the crash, which will at least make this a non-critical issue.

Can you review and (assuming it works) merge (FYI, I did run test.sh lmfdb/ecnf)?

**Comment by JohnCremona** [comment] 2016-05-07 15:09
Done.  Will push to beta & prod now (though there will be a delay until the
prod code gets picked up by the cloud).

**Comment by JohnCremona** [comment] 2016-05-07 15:15
Fixed on beta and prod@warwick.  Can be closed once cloud has it too and www.lmfdb.org/EllipticCurve/3.3.1016.1/9.2/b/3
works without crashing

**Comment by jvoight** [comment] 2016-05-07 15:36
Works in the cloud without crashing, displays "unable to plot".

**Comment by roed314** [comment] 2016-05-07 20:31
I'm not going to get a chance to look at this until Monday, but I can once
I get to AIM. And it sounds like it might already be resolved....

**Comment by AndrewVSutherland** [comment] 2016-05-07 20:41
@roed314 The only thing that remains unresolved is whether the error "No horizontal tangent lines on bounded component" being raised by the plot function is expected behaviour (so we really cannot plot this curve), or not.  If you can confirm that it is expected behaviour then I'm happy to close.

**Comment by jvoight** [comment] 2016-05-07 20:47
I just pinged @nmascot by email to see what he thinks.  JV

**Comment by nmascot** [comment] 2016-05-07 23:47
Hi,

I've only just received @jvoight 's ping.

I have to catch a plane early tomorrow (well, later today in fact); I'll have a closer look at it as soon as I can (= tomorrow afternoon).

Overall I have the impression that Sage's elliptic curve plot function is messy and unreliable (I have already had to include one specific workaround in the past because of that), so I think I'll just adapt my genus 2 plotting code and not call Sage's function anymore.

**Comment by nmascot** [comment] 2016-05-08 20:57
I've just written new code. It seems to work fine, even for EllipticCurve/3.3.1016.1/9.2/b/3 . The error was caused bu this curve having huge coefficients, which became even more ridiculous when specialised to R via some real embedding of the ground field; Sage's elliptic curve plotting function simply could not cope with that.

**Comment by nmascot** [comment] 2016-05-08 21:03
Merge just requested (#1244)

**Comment by AndrewVSutherland** [comment] 2016-05-18 23:48
This was fixed by #1244 which is now on www.lmfdb.org.  The page http://www.lmfdb.org/EllipticCurve/3.3.1016.1/9.2/b/3 (and others) now shows a plot without any errors.

Closing

**Closed by AndrewVSutherland** 2016-05-18 23:48 UTC
Labels: ecnf
