### ISSUE TITLE
Downloading elliptic curves can give too many

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5641] opened 2023-08-15 20:17 UTC
From the feedback page:

When I search for elliptic curves by conductor and select "one per isogeny class", the website correctly displays only one curve per isogeny class (in this case 10293 results). But when I download the data (I have tried gp and sage) the file gives me more than one curve per isogeny class (16494 curves). This example was for selecting conductor in the range 7500-10000 and "one per isogeny class". Thank you for your time.

**Comment by roed314** [comment] 2023-09-08 06:39
This is a duplicate of #5091

**Closed by roed314** 2023-09-08 06:39 UTC
Labels: ECQ, downloads
