### ISSUE TITLE
EC/ECNF: search by size of isogeny class

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#1483] opened 2016-06-01 09:22 UTC
**_1 Upvote**_ It would be nice to be able to search elliptic curves by size of the isogeny class (<=, ==, >=). This should be possible with the existing data using the fact that the elliptic curves in an isogeny class are labelled 1, ... , size of isogeny class.

**Comment by AndrewVSutherland** [comment] 2016-06-01 09:39
+1 I would like to have this feature too, and I agree that an search would be very easy to implement (just query on the "number" attribute).

Doing an interval search would require a little more thought (you would want to project down to one record per isogeny class).  The non-trivial part of this would be implementing browse/search pages for isogney classes, which do not currently exist.  On the other hand, implementing a search for curves **contained** in an isogeny class of a given size would be trivial (just a few lines of code and one new input box on the search pages).

**Comment by JohnCremona** [comment] 2016-06-01 11:36
I think there may be a small misunderstanding here: the 'number' field is the index of a curve in its class, so searching for {'number':5} will find a curve in every class whose size it at least 5, not exactly 5.  To avoide awkward code we could store the size ofthe isogeny class with every curve, or with one curve per class.  So far we have managed to avoid having a separate collection for isogeny classes, and hope that we can continue to avoind that.  There are some data fields which only exists for one curve per class already, including the isogeny matrix which is a list of lists of ints, so if one can search for objects for which a list field has a certain length then Aurel's request would be easy (if not necessarily efficient).

It is possible:

nfcurves.find_one({'isogeny_matrix':{'$size':int(18)}})

**Comment by AndrewVSutherland** [comment] 2016-06-01 11:47
@JohnCremona You are right of course, I responded to quickly.

**Comment by JohnCremona** [comment] 2017-04-22 10:25
Over Q  each curve now has fields 'class_size' and 'class_deg' being the size of the isogeny class and the maximal degree of a cycylic isogeny between curves in the class.  This is displayed on each curve's home page.  We just implemented search by isogeny degree (returning all curves with a cyclic isogeny (not an endomorphism) of the given degree(s)) and it would be simple to add searches by these other two parameters.
Over number fields I also just implemented search isogeny degree but forgot to add the two additional fields to each curve, so that will need doing before implementing the above for ecnf, unless it is done using code like I suggested earlier.

**Comment by AndrewVSutherland** [comment] 2017-04-22 11:41
It probably makes sense to do this for number curves as well.

**Comment by JohnCremona** [comment] 2019-03-25 12:47
Since the conversion to postgres put the class_size column into the extra table, it is no longer possible to search on the class size, so this cannot be implemented.  This seems to me to be a regression.

**Comment by AndrewVSutherland** [comment] 2019-03-25 14:01
We should move this column to the search table (no column *has* to be in the extras table, this is just a performance optimization, we can put everything in the search table if desired. For a column this small there is no performance benefit to having it in the extras table -- we can easily fix this (but let me talk to @roed314 about the best way to do this without causing any disruption -- I think we can just add it to the main table and delete it from the extras table, but I'm not sure whether db backend exposes an interface that lets you do this in one step, but it should be easy to provide a method that does this).

**Comment by JohnCremona** [comment] 2019-03-25 14:06
OK -- no hurry.  It is a pity that the division into search+extra tables happened without more discussion first.

**Comment by roed314** [comment] 2019-03-31 08:10
I've manually moved `class_size` from `ec_curves_extras` to `ec_curves`.  There are no indexes for it yet, but you should be able to try to implement this feature now.

**Comment by JohnCremona** [comment] 2020-12-03 11:20
In my new ECQ schema I have class_deg in the main table ec_curvedata but not class_size, which is in the table ec_classdata, though the class size can be obtain as the length of the list 'isogeny_degrees' in the main table.  In order to be able to search on class size, I'll add/move it to the main table.

**Comment by JohnCremona** [comment] 2021-02-09 15:30
This is already implemented for EC/Q.  It will be easy to also implement it for EC/NF since there is now a 'class_size' column.  I just made a small PR which is rather similar, so I will add this option to that.  See PR #4434

**Comment by AndrewVSutherland** [comment] 2021-02-12 19:39
Closed via #4434

**Closed by AndrewVSutherland** 2021-02-12 19:39 UTC
Labels: ECNF, ECQ, feature request
