### ISSUE TITLE
broken L/NumberField/14.14.28152039412241052225421312.1/

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#12] opened 2013-01-29 09:02 UTC
the page http://www.lmfdb.org/L/NumberField/14.14.28152039412241052225421312.1/ *maybe* worked before and is broken now

**Comment by haraldschilly** [comment] 2015-10-27 17:57
see issue #430

**Comment by jvoight** [comment] 2015-11-04 21:24
This number field doesn't even exist any more, so that might be why it doesn't have an L-function!  http://beta.lmfdb.org/NumberField/14.14.28152039412241052225421312.1/

**Comment by jwj61** [comment] 2015-11-05 01:59
Interesting.  I don't recall deleting any fields, but since it is not there, the issue is closed.

**Comment by jwj61** [comment] 2015-11-05 16:12
On a closer look, this field does exist.  JV didn't see it because of the trailing slash in the url.  This should be readily fixed once the L-function database extends far enough since it is an abelian field, so it will just need to reference some Dirichlet l-functions.

**Comment by jvoight** [comment] 2015-11-05 16:19
My mistake!  I just copied the link from the top (deleting the L).  (It looks like the L-function page redirects; should we do the same for number fields?)

**Comment by jwj61** [comment] 2015-11-05 16:25
Probably, but I think this is a general issue.  I tried the analogue with a specific elliptic curve page, and adding a slash put me on the search results page.

**Comment by JohnCremona** [comment] 2016-05-02 14:57
Why is this critical?

**Comment by davidfarmer** [comment] 2016-05-02 15:31
I marked it as critical because it is a link that shows
a bad error.

My most recent pull request hides the links to Dedekind
zeta functions that are too big to computer on the fly, so
I removed the critical label.

The proper fix will come when we have those L-functions
in a database.

**Comment by jwj61** [comment] 2016-06-08 18:15
I am not sure this deserves a production problem label since there is no place in the lmfdb which links to this page.  Some day, that L-function may come back (which involves the addition of more L-function data, and building the mechanism for products of L-functions).  This is more like a feature request, or really a byproduct of two or three planned features.

**Comment by AndrewVSutherland** [comment] 2016-06-08 18:20
Agreed.

**Comment by AndrewVSutherland** [comment] 2016-07-10 17:54
This issue is fixed by PR #1701, which by preventing the computation of special values for number field L-functions of degree > 4 allows this page to load correctly.

**Comment by AndrewVSutherland** [comment] 2016-07-10 19:59
Closed via #1701.

**Closed by AndrewVSutherland** 2016-07-10 19:59 UTC
Labels: Lfcns
