### ISSUE TITLE
Number field grd rendering error

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5907] opened 2024-03-09 22:59 UTC
```
Exception on /NumberField/16.4.604462909807314587353088.28 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/number_field.py", line 745, in by_label
    return render_field_webpage({'label': nflabel})
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/number_field.py", line 470, in render_field_webpage
    data['grd'] = nf.grd()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/web_number_field.py", line 490, in grd
    exps = [str(QQ(z/galord)) for z in exps]
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/web_number_field.py", line 490, in <listcomp>
    exps = [str(QQ(z/galord)) for z in exps]
TypeError: unsupported operand type(s) for /: 'list' and 'int'
[2024-03-09 22:41:15 UTC] 500 error on URL https://www.lmfdb.org/NumberField/16.4.604462909807314587353088.28 ()
```

**Comment by jwj61** [comment] 2024-03-09 23:47
Looks like a data error.  Working on it ...

**Comment by jwj61** [comment] 2024-03-09 23:52
As best as I can tell, the problem is confined to the global fields of degree 16 which came from the p-adic square.  After my first stab at fixing it, the page renders on beta, and the grd should be right, but the exponent(s) in the factorization are not.

**Comment by jwj61** [comment] 2024-03-10 21:14
It should all fixed now on beta.

**Comment by roed314** [comment] 2024-03-11 00:27
So should @edgarcosta push `nf_fields` to production?

**Comment by jwj61** [comment] 2024-03-11 01:37
Let's do that tomorrow; there is some more grd data which will be ready to upload this evening.

**Comment by jwj61** [comment] 2024-03-11 02:37
OK, new stuff added.  It can be pushed to production when it is convenient.

**Comment by edgarcosta** [comment] 2024-03-11 20:09
in progress

**Comment by jwj61** [comment] 2024-03-12 02:49
I assume it is done by now

**Closed by jwj61** 2024-03-12 02:49 UTC

**Comment by edgarcosta** [comment] 2024-03-12 15:11
it is done
