### ISSUE TITLE
Random Classical Modular Form

### ISSUE THREAD

**Issue by grundman7** [LMFDB/lmfdb#3332] opened 2019-09-06 21:18 UTC
I don't see a place to find a random classical modular form (or newform or newspace) on http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/

Similarly for Maass and Bianchi forms

**Comment by roed314** [comment] 2019-09-06 21:32
For classical modular forms, the random link is at the end of the list of interesting forms.  You can also get a random form by clicking on the random button below the search boxes.

For Bianchi forms, the random link is just above the search inputs.

I don't see a link for Maass forms, but they generally need some work.

**Comment by davidfarmer** [comment] 2019-09-06 21:41
The list of interesting modular form links would be better if each link said why it is interesting.
Elliptic curves over numbers fields gives an example of this.
Once that change is made, it will be natural to also make the random link more visible,
and more uniform with how it is on other pages.   (I think the lack of uniformity across pages
is the cause of this issue being submitted.)

**Comment by roed314** [comment] 2019-09-06 21:46
The reason is given in hovertext for each interesting form.

**Comment by roed314** [comment] 2019-09-06 21:47
I'd actually like to make other pages more like modular forms, in that there's a button to get a random modular form satisfying constraints provided in the search boxes.

**Comment by davidfarmer** [comment] 2019-09-06 21:58
The hovertext is not something that a typical user would notice.

**Comment by jwj61** [comment] 2019-09-06 22:05
To echo David's point, no one here noticed the hovertext.

I agree that other areas should also have a random button to go with the search area, but the random link for modular forms should be positioned like other pages.

**Comment by edgarcosta** [comment] 2019-09-11 20:42
Should we make it a norm that all the "interesting" objects on the homepage should have top/bottom knowls saying why they are interesting?

**Comment by davidfarmer** [comment] 2019-09-11 21:03
Most interesting things are not interesting enough to merit a top knowl.

But I think we agreed that the threshold to be in the bottom knowl
is much less strict.

In particular, the "largest known example" does not (in my opinion)
merit being in the top knowl.  Being the smallest of something might
merit top knowl mention, but not always.

**Comment by jvoight** [comment] 2020-09-11 15:16
We have a proposal for how to address this, Drew will be mocking something up.

**Comment by AndrewVSutherland** [comment] 2020-09-25 17:58
Addressed by #4032

**Closed by AndrewVSutherland** 2020-09-25 17:58 UTC
Labels: CMF
