### ISSUE TITLE
elliptic curve pages are slow

### ISSUE THREAD

**Issue by jwbober** [LMFDB/lmfdb#1199] opened 2016-05-06 14:14 UTC
Every request for the url www.lmfdb.org/EllipticCurve/Q/1001.b/ results in two database queries (copied from the mongodb log):

`2016-05-06T15:09:51.046+0100 I COMMAND  [conn57] command elliptic_curves.$cmd command: count { count: "nfcurves", fields: null, query: { conductor_label: "1001.b" } } planSummary: COLLSCAN keyUpdates:0 writeConflicts:0 numYields:2498 reslen:44 locks:{ Global: { acquireCount: { r: 4998 } }, MMAPV1Journal: { acquireCount: { r: 2499 } }, Database: { acquireCount: { r: 2499 } }, Collection: { acquireCount: { R: 2499 } } } 287ms`
`2016-05-06T15:09:51.646+0100 I QUERY    [conn57] query elliptic_curves.nfcurves query: { $query: { conductor_label: "1001.b" }, $orderby: { field_label: 1, conductor_norm: 1, conductor_label: 1, iso_nlabel: 1, number: 1 } } planSummary: COLLSCAN, COLLSCAN ntoreturn:50 ntoskip:0 nscanned:0 nscannedObjects:639502 scanAndOrder:1 keyUpdates:0 writeConflicts:0 numYields:4996 nreturned:0 reslen:20 locks:{ Global: { acquireCount: { r: 9994 } }, MMAPV1Journal: { acquireCount: { r: 4997 } }, Database: { acquireCount: { r: 4997 } }, Collection: { acquireCount: { R: 4997 } } } 598ms`

(I don't know why this is happening.)

**Comment by JohnCremona** [comment] 2016-05-06 19:19
If you out in a URL like EllipticCurve/Q/1001.b it does a database query to see if the label exists and if it does then calls another function which gets the data.  This has been true for a very long time and similar things happen all over the place, e.g. HMFs where I tried recoding to avoid this and the results was a lot worse.

I have removed the critical label since no-one has been at all bothered by this for years.

**Comment by jwbober** [comment] 2016-05-06 21:14
I think you misunderstand the queries that I copy-and-pasted. It is doing
number field queries, looking for whether the elliptic curve label it is
looking for us also the label of the conductor of an elliptic curve over a
number field. Also, it is counting elliptic curves over number fields.

These things are really slow, and it makes no sense that they are
happening.

**Comment by JohnCremona** [comment] 2016-05-06 21:28
OK, I did misunderstand.   Perhaps the problem is the the URL EllipticCurve/Q/label could be routed through blueprint EllipticCurve/Q or through EllipticCurve/
That would not explain the counts though.  I'll look into it tomorrow.

**Comment by AndrewVSutherland** [comment] 2016-05-06 21:50
@jwbober, @JohnCremona +1 I think this is worth looking at.

**Comment by jwbober** [comment] 2016-05-07 01:34
I realize now that this issue is different than I thought it was, and probably also not as big a deal as I thought it was.

I got this url by manually removing a "/L" from an L function url, and I guess I didn't actually pay attention to what I was getting (since I was timing things using wget). No one should actually do this unless they (think that they) know what they are doing. It seems that the (or an) actual problem has to do with how the trailing / is handled. If you removing the / at the end of the URL I posted you get a different page, which is not so slow, and which I guess is the page that I was actually expecting to get.

I guess that somewhere we lost track of the idea that putting in (or removing) a /L in the right place in the URL should take you to (or away from) an L function page, and I don't know right now what the right way to fix that is.

(It is still odd to me that a search page for elliptic curves over Q ends up counting elliptic curves over number fields and doing a query for the conductor of elliptic curves over number fields, but maybe this is not really supposed to be a working url anyway.)

**Comment by JohnCremona** [comment] 2016-05-07 09:58
@jwbober has this just about right.  (1) For elliptic curves over Q all the following URL schemes work:
EllipticCurve/Q/11 # just a search output
EllipticCurve/Q/11/a } shows the isogeny class
EllipticCurve/Q/11.a }  shows the isogeny class
EllipticCurve/Q/11/a/1 } shows the curve
EllipticCurve/Q/11.a1 } shows the curve
EllipticCurve/Q/11/a1 } shows the isogeny class !! not right

while the same flexibility is not allowed for URLs with L/ in front.

(2) For elliptic curve in general the prefix is EllipticCurve/ without the Q/ and we rely on flask foing the right thing, which I understood to be that if there is a Q/ there then it uses the full EllipticCurve/Q/ as prefix for the blueprint ec while if there is anything other than Q it uses the prefix EllipticCurve/ for the blueprint ecnf.

It seems to be this last point which is not working as intended, so that some EllipticCurve/Q/ URLs are causing the ecnf blueprint to be activated; luckily the end result is the correct page but some time is wasted.

Despite that there is *absolutely* no reason why going to any individual curve's page should cause any count operations to be done.  (I do not count a database query for all the curves in an isogeny class followed by calling count() on the returned iterator.)

This kind of thing is not easy for developers to catch since they do not (mostly) have access to the mongo logs.  I'll spend a bit of time on this later today.

**Comment by JohnCremona** [comment] 2016-05-07 10:15
@jwbober I have tried to recreate the thing you reported on here: on beta.lmfdb.org (so at Warwick not the cloud) I go to URLs like EllipticCurve/Q/1001.a or EllipticCurve/Q/990.b (for a change) and cannot see any log entries in home/lmfdb/db/mongo.log which match.

**Comment by edgarcosta** [comment] 2016-05-07 15:01
I'm not sure if this helps, but when I profiled it locally, connected directly to the mongodb server, most of the time was spent talking with the mongodb server: https://gist.github.com/anonymous/3d604810147cc993ad3b21efc62b9346

**Comment by jvoight** [comment] 2016-05-08 17:15
I don't know if this will help, but in #1243 I tried to remove some code that was using counts.  We could try to merge it, see if it improves things, and revert if it doesn't do enough.

**Comment by JohnCremona** [comment] 2016-05-09 01:15
Drew found that there was a missing index which slowed down the counting of
isogeny classes.  He added the extra index and now EllipticCurve/Q  loads
faster.

**Comment by davidfarmer** [comment] 2016-05-09 22:12
fixed, so closing

**Closed by davidfarmer** 2016-05-09 22:12 UTC
Labels: ec, ecnf

**Comment by edgarcosta** [comment] 2016-05-09 22:17
@AndrewVSutherland  fixed : http://www.lmfdb.org/EllipticCurve/Q/ and http://www.lmfdb.org/EllipticCurve/
but a random elliptic curve still takes 3+s to load

**Comment by AndrewVSutherland** [comment] 2016-05-09 22:22
@edgarcosta @davidfarmer I agree that random elliptic curves are still too slow but I'm happy to view this as part of the https://github.com/LMFDB/lmfdb/issues/1247 thread (there are other places where random objects are slow and having the discussion all in one place can help spread/share the knowledge of how to fix it).

**Comment by edgarcosta** [comment] 2016-05-09 22:30
okidoki

**Comment by JohnCremona** [comment] 2016-05-09 22:36
How much of the time taken for the random ec to load is in fteching the random object from the database, and home much from processing that curve?

Here's what happens when we make an ecnf web page:
- the corresponding Sage elliptic curve object is created
- its conductor is computed and factored (without the need to factor it we could of course construct the conductor from the db)
- the discriminant ideal is computed and factored.  This involves working out whether we have a global minimal model, of if not then at which primes it is non-minimal
- the regulator of the generators is computed.  (We have gens for rather few of the curves in the db and I need to be reminded to store the regulator of any points which we do have.
- the local data data at all primes of bad reduction is computed from the Sage curve

OK, so that is a terrifying list, and I should rewrite a lot of how I manage these curves.  Not having to create the Sage curve and compute that stuff from it on the fly should be a priority.

**Comment by JohnCremona** [comment] 2016-05-09 22:36
I'll make an issue for the above.
