### ISSUE TITLE
Broken ECNF pages

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5398] opened 2023-03-10 17:40 UTC
https://www.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1
https://www.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/2

```
Exception on /EllipticCurve/2.0.7.1/12544.5/CMa/1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 282, in show_ecnf
    ec = ECNF.by_label(label)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/WebEllipticCurve.py", line 334, in by_label
    return ECNF(data)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/WebEllipticCurve.py", line 325, in __init__
    self.make_E()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/WebEllipticCurve.py", line 541, in make_E
    assert self.ar=="not available" or (self.rk_lb<=self.analytic_rank and self.analytic_rank<=self.rk_ub)
AssertionError

**Comment by JohnCremona** [comment] 2023-03-10 17:55
Probably an error in recently uploaded data. Caused by Magma computing analytic ranks wrongly for curves with rational CM.  (It detects that the L function is a square but forgets to double.) At least that used to be the case, but I reported the bug, and if it is now fixed then my wrapper fixing it may have doubled again unnecessarily. Only affects curves with CM Iin the label

**Comment by JohnCremona** [comment] 2023-03-10 19:11
Probably an error in recently uploaded data. Caused by Magma computing analytic ranks wrongly for curves with rational CM.  (It detects that the L function is a square but forgets to double.) At least that used to be the case, but I reported the bug, and if it is now fixed then my wrapper fixing it may have doubled again unnecessarily. Only affects curves with CM Iin the label

I will try to fix this tomorrow

**Comment by JohnCremona** [comment] 2023-03-10 21:00
Diagnosis was correct.  This affects 26 curves all of which have rank 2 (lower and upper bounds 2) but analytic rank set to 4.  Data fix under way.

We should not reall have assert statements in live code (though it helped find this bug).

**Comment by JohnCremona** [comment] 2023-03-10 21:06
Done: see https://beta.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1 for the failure noted above which is now fine.

There were 27 affected curves, all over IQ fields of class number 1, with rational CM, rank 2, but analytic rank had been doubled because of my code fixing a magma bug which is now fixed upstream.

Sorry.

**Comment by AndrewVSutherland** [comment] 2023-03-10 21:59
I copied ec_nfcurves to prod so that https://www.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1 also works again.

**Comment by JohnCremona** [comment] 2023-03-11 14:59
Reason for repoening: although I did fix the 27 bad analyic rank values (all were 4 and not 2 because of incorrect doubling), I did not at the same time fix the bad special L-values (all were incorrectly squared).  As well as this meaning that the 27 curves have incorrect L-values, it also meant that these curves have no (or incorrect) analytic Sha.

Example:  https://beta.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1 shows the L-value ("leading coefficient") to be 6.3788509364311350553931977635600000000 but it is 4.87333797204966334760749969350 (Magma and GP agree to 30dp on this).

I probably should not have tried to fix the issue in a hurry yesterday, but at least the remaining issue will not casue a crash.

**Comment by JohnCremona** [comment] 2023-03-11 16:16
I found some more normalization issues with the BSD quantities, which deserve a new issue, so I will reclose this after opening that.

See #5409

**Comment by JohnCremona** [comment] 2023-03-12 16:37
I fixed the second issue regarding leading coefficient (L-value) and analytic Sha for curves with rational CM (over IQFs of class number 1).  For example see  https://beta.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1 or most such curves: the L-value is now different (and without the supicious trailing zeros) and the Sha value is not missing.

So: one more copy of ec_nfcurves to prod please.

**Comment by AndrewVSutherland** [comment] 2023-03-12 16:42
Done, see https://www.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1

**Comment by JohnCremona** [comment] 2023-03-12 16:50
> Done, see https://www.lmfdb.org/EllipticCurve/2.0.7.1/12544.5/CMa/1

Thanks Drew, I hope this is the last of this glitch!

**Closed by JohnCremona** 2023-03-12 16:50 UTC
Labels: ECNF
