### ISSUE TITLE
Error in genus 3 curve family data

### ISSUE THREAD

**Issue by koffie** [LMFDB/lmfdb#2223] opened 2017-08-13 17:44 UTC
The page http://www.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2.1 says that the curves in that family are Hyperelliptic. But this makes no sense given that the equation there is a smooth plane quartic, and smooth plane quartics are never Hyperelliptic. 
I also think that the Jacobian decomposition data is incorrect. This curve has three different involutions. Each involution yielding a map to a different genus 1 curve whose pullback to the jacbonian is distinct from the elliptic curves obtained from the other involutions. Hence the jacobian should decompose as three (possibly non isogenous) elliptic curves.

**Comment by JohnCremona** [comment] 2017-08-13 18:21
@jenpaulhus ?

**Comment by AndrewVSutherland** [comment] 2017-08-13 18:51
Jen should chime in here, but I believe that a family is tagged as "hyperelliptic" if it contains a hyperelliptic curve -- this does not imply that all curves in the family are hyperelliptic.  For example, in genus 3 there is only one family listed for the cyclic group of order 2 (see http://www.lmfdb.org/HigherGenus/C/Aut/?genus=3&group=%5B2%2C1%5D).  But this family necessarily contains both hyperelliptic and non-hyperelliptic curves.

**Comment by jenpaulhus** [comment] 2017-08-13 22:10
Drew is basically correct.  But there is still a small error.  The issue is in the equation.   If you go back to the family: http://www.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2  you can see there are 7 inequivalent actions.  Six of them are hyperelliptic (1,2,3,5,6, and 7 in my numbering scheme) and each of those individual pages is displaying the wrong equation.  (And the Jacobian decomp is correct.)

Only one of then is non-hyperelliptic:
http://www.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2.4
For this one the equation is correct (and notice the Jac Decomp  is ExExE here).

I'll have to go back into the code and see why that one equation is recording for all curves in the family.  Thanks for pointing this out.

**Comment by koffie** [comment] 2017-08-14 00:14
Yes all my reasoning above was based on the equation, so if the equation shown was wrong, then the rest of the data might well be correct. I did some digging around, and the equations seem to always be the same for other families as well. At least the two other ones I looked at http://www.lmfdb.org/HigherGenus/C/Aut/3.16-11.0.2-2-2-4  and http://www.lmfdb.org/HigherGenus/C/Aut/3.8-5.0.2-2-2-2-2

**Comment by jenpaulhus** [comment] 2017-08-15 15:02
@koffie So these other two examples you linked are "working as intended".  That's because the equations I list for hyperelliptic curves come from Shaska's paper "Determining the Automorphism Group of a Hyperelliptic Curve." His equations are  up to the automorphism group and signature, they aren't for each individual refined passport.  It is possible for low genus we may ultimately want specific equations for each refined passport, but I don't know of an obvious way to compute that right now. If you know a way to that, I'd be happy to hear about it and include that in the data. 

It might be best for me to move the equations out to the passport pages, instead of the refined passport pages.  I'll have to think about that a bit.

The first example you listed is an error in my code, and I will fix that soon (and only an error in genus 3, which is the only genus I list equations for the non-hyperelliptic examples). In the meantime, if you need the equations for those hyperelliptic curves, it's:
y^2=x(x − 1)(x^5 + a_1x^4 + a_2x^3 + a_3x^2 + a_4x + a_5)

@AndrewVSutherland  The example you linked for genus 3 and the cyclic group of order 2 was bothering me.  Within a _refined_ passport, all examples should be hyperelliptic or non-hyperelliptic.  The reason that my data is only showing the hyperelliptic case in genus 3 is that the non-hyperelliptic case is a cover of a genus 1 curve, not P^1, and I only currently have examples with orbit genus 0.  I'm hoping to implement orbit genus >0 pages sometime this fall.

**Comment by AndrewVSutherland** [comment] 2017-08-15 15:32
@jenpaulhus I think it would be a good idea to add a Completeness link to the "learn more about" panel that explains exactly what information is currently available (see genus2 curves, elliptic curves, or number fields for examples of this).

**Comment by jenpaulhus** [comment] 2017-08-15 16:06
I do have something written here about the quotient genus:
http://www.lmfdb.org/HigherGenus/C/Aut/Completeness

And something here about where the equations come from:
http://www.lmfdb.org/HigherGenus/C/Aut/Source

Would it be helpful to elaborate on those?

**Comment by AndrewVSutherland** [comment] 2017-08-15 16:18
Ah, I was confused by the fact that the completeness link is not shown on the main browse page (it is on the genus 2 pages and number field pages, but not on the elliptic curve pages.  For consistency I think the completeleness link should be shown on the main browse page (both in the automorphism families and on the elliptic curve pages), since this is where a user would look for it, and in general it may contain more information than you want to display on the main browse page.

In terms of the content, I think you could perhaps expand the completeness knowl a bit (both in terms of explanation and some numbers would be nice (e.g. how many groups, how many passports, etc...).

**Comment by jenpaulhus** [comment] 2017-08-15 16:44
Great, I'll make those fixes/additions soon-ish.

**Comment by JohnCremona** [comment] 2017-08-15 18:15
@AndrewVSutherland "... it __may__ contain ...":  in the case of http://www.lmfdb.org/EllipticCurve/Q/ the information already shown at the top of the page is precisely the content of http://www.lmfdb.org/EllipticCurve/Q/Completeness which is seen in some other places.   In fact that's a tautology since both just display the knowl http://www.lmfdb.org/knowledge/show/dq.ec.extent .
So, do you still want to see "Completeness of the data" under "Learn more about" on http://www.lmfdb.org/EllipticCurve/Q/ ?

**Comment by AndrewVSutherland** [comment] 2017-08-15 18:33
@JohnCremona I realize the information is exactly the same in the case of elliptic curves, but I think it is still helpful to have the completeness link visible (if I'm naive user who has used other parts of the LMFDB, that is where I'm likely to look).  It's also a bit confusing that when I go into one of the "Learn More" links that is there (e.g. labels), the completeness link suddenly appears.

Also, for elliptic curves over number fields, I think it would be nice if the completeness knowl gave more informations (e.g. a description of the number fields covered and conductors bounds within them).  I find it confusing that on the page http://www.lmfdb.org/EllipticCurve/browse/, clicking on the completeness link actually takes away information on the page relevant to completeness.

I guess the scenario I'm imagining is one in which I'm a researcher who has a mathematical object that is of interest to me (e.g. an elliptic curve over a number field), but I can't find in the LMFDB and I want to know why it's not there (maybe I found something the LMFDB folks missed!).  The completeness link should tell me why it isn't in the database.

**Comment by JohnCremona** [comment] 2017-08-15 18:49
OK, this does need more thought.  The ecnf pages have rather more detail in the "source" knowl (http://www.lmfdb.org/EllipticCurve/Source) than in the extent knowl which is a very short summary (short enough to appear at the top of the main page!).   A lot of curves have been added over the past year so the Source page is out of date anyway (especially for imaginary quadratics).

Adding the range of fields and conductors will add a lot to the completeness page!  For example, over quadratics it would contain everything in http://www.lmfdb.org/EllipticCurve/browse/2/.  Not easy from the design point of view!

**Comment by AndrewVSutherland** [comment] 2017-08-15 18:57
@JohnCremona surely there Is there some rhyme or reason as to which curves over quadratic fields are in the database?  Is there a concise way to characterize this (e.g. for real quadratic fields of discriminant up to 500 we include all curves such that ....)?

**Comment by edgarcosta** [comment] 2017-08-15 18:59
I agree with Drew.
If something is not on the LMFDB I want to know why. (even though there are exceptions)
For example, pick a genus 2 curve or an elliptic curve over QQ , if I search it on the LMFDB and I don't find it, it is easy to see why isn't there.
However, for elliptic curves over number fields, Lattices, etc, is not clear what are the parameters...

**Comment by JohnCremona** [comment] 2017-08-15 19:06
@AndrewVSutherland @edgarcosta Over totally real fields there certainly is a rhyme and reason:  I simply found curves for all (but a few over sextic fields) Hilbert modular forms with rational a_P.  So the bizarre distribution of conductor norm bounds arises simply because they are the level norm bounds for the HMFs, which in turn have no better explanation (as @jvoight has explained) than "over each field we kept going until we found a space which we could not split into new irreducible pieces".  So the elliptic curve ranges are a consequence of that.  If someone would like to extend the HMF data, I would be happy to find the extra curves.  It is possible (in that Magma provides this functionality) to only split off one-dimensional pieces.  That's what I do over imaginary quadratic fields (where I myself an in control over the extent of both the Bianchi newforms and the elliptic curves, by contrast with the totally real situation).  So a nice project for someone else would be to do that.  But not me, I have other things to do.

I have spent many hundreds of hours finding these curves over totally real fields.  Am I really now under attack for not spending more?

**Comment by AndrewVSutherland** [comment] 2017-08-15 19:21
@JohnCremona Of course not, quite the opposite!  I love the new ecnf data and appreciate all the hard work that went into it, I'd just like to understand what is there.  I certainly didn't mean to add more work to your to do list (which I know is already quite long!). 

If there is not an easy way to describe things on the elliptic curve side, then maybe the thing to do is to describe the situation over real quadratic fields with something like "we have a total of N elliptic curves over every real quadratic field of discriminant up to 500.  The lists are complete up to a conductor bound that varies with the field (click *here* to see the list of conductor bounds)" where *here* points to http://www.lmfdb.org/EllipticCurve/browse/2/2/.   But there is no rush to do any of this, it can certainly wait!

**Comment by edgarcosta** [comment] 2017-08-15 19:37
Sorry, @JohnCremona <https://github.com/johncremona> that was in no way
meant as an attack! It was more a generic *it would be nice if*  we could
have a clear description of the completeness of all the data in the LMFDB.
It might not be possible to declare the data "complete" in any form, but
then we should also say it.

**Comment by jvoight** [comment] 2017-08-15 23:55
Sorry y'all, it's true, I didn't really see a clean cutoff for the levels of HMFs, and just computed some data for each field (always complete up to a given level norm).  I don't think we'll ever have enough elliptic curves, modular forms, etc., to make everyone happy, but we do want enough so that people can see what's there.  I thought 250 GB of HMFs would do that!  

We absolutely could get more HMFs with rational Hecke field <-> elliptic curves this way; but it would only be over totally real fields, and pretty soon someone will ask for the abelian surfaces as well, and forms with character and higher weight, and on and on.

Luckily, we have been generously funded (!) for precisely such an ambitious extension of the data.  I don't think we should feel bad or ever under attack for what we have now--we should enjoy it, using it as a very strong basis upon which to have data for LMFDB 2.0.

That being said, even in LMFDB 10.0 (god help us), I'm not sure we'll ever have a good reason for data not appearing in the database other than "we stopped here".  Edgar, is there an explanation which is ever better than that?

**Comment by AndrewVSutherland** [comment] 2017-08-16 00:06
@jvoight "We stopped here" is a perfectly good explanation!  I think all Edgar and I are asking for is the ability to easily determine where "here" is.  There is a crucial difference between data that is missing because it is past the point where we stopped and data that is missing because of an error.

**Comment by edgarcosta** [comment] 2017-08-16 00:28
@jvoight, Sorry for not being clear.
That is exactly what I would love to have, the "We stopped here"  where the
"here" is specified.

In short, I want to know that if I can't find it in the DB then it does not
exist (under certain conditions). Or if I only find one, then it's unique.
At the end of the day, I would like us to be clear until what point the
data is complete and if it is not exhaustive in any way we should clearly
state that. Otherwise, is hard to distinguish between agglomerates of
interesting examples and exhaustive tables.
All this is easier said than done, but I would love us to walk towards that.

**Comment by JohnCremona** [comment] 2017-08-16 07:45
Apologies for my unfortunate choice of words (now edited).  I have been putting off the job of improving the description of which elliptic curves we do have, partly because it's not so easy to design (with hundreds of fields all with different rnges) and partly because the exact situation has been changing quite rapidly.  At least now we have no gaps  in degrees <6 and even in degree 6 "only" are missing 55 curves over 13 of the 34 fields.  But the enhanced extent/completeness web page would have to detail the missing cases.  (There are also some missing curves over 2.0.4.1 and 2.0.3.1.)

**Comment by koffie** [comment] 2017-08-16 14:27
@jenpaulhus I don't know to much about trying to find explicit equations myself but this sounds like an interesting computational problem to study, you undoubtedly know more about this then I do.  There seems to be a [recent paper](http://www.ams.org/journals/mcom/2017-86-305/S0025-5718-2016-03116-6/S0025-5718-2016-03116-6.pdf) of Joachim König about explicitly computing Hurwitz spaces (I didn't read the paper yet so I don't know wether the techniques he uses are bound to the groups that he uses or that his computations can be extended to other groups as wel).

On a side note, what is the way I would go and correct some knowls (I don't have a login account on lmfdb.org yet). The knowls on [generating vector](http://www.lmfdb.org/knowledge/show/curve.highergenus.aut.generatingvector) and [monodromy group](http://www.lmfdb.org/knowledge/show/curve.highergenus.aut.monodromy) seem to mix up Y-B and Y

**Comment by JohnCremona** [comment] 2017-08-16 14:33
@koffie I'll email you so as to give you a login to add and correct knowls.  Note that this __must__ be done on beta.lmfdb.org: not on www.lmfdb.org, and also not on a local instance of the website.

**Comment by jenpaulhus** [comment] 2017-09-17 17:05
The equation issue is now fixed on beta.  I wasn't sure if you automatically update data on the production site occasionally or if I needed to request that it be updated.  

You can see the difference at:
http://beta.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2.4
http://beta.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2.1
(non-hyperelliptic example first, and hyperelliptic example second)

As a short term fix for having more description of what's going on for these pages, I've added a link to a preprint I have which describes in much greater detail the data on these pages (you can see it at the top of this page: http://www.lmfdb.org/HigherGenus/C/Aut/Source). When I have a chance, I will add more of that information directly onto the Source and Completeness knowls.

I will have a pull request in the not so distant future that takes care of moving that "Completeness" knowl off the top of the main page.

**Comment by AndrewVSutherland** [comment] 2017-09-17 17:18
@jenpaulhus I just updated the data on the cloud, see

http://www.lmfdb.org/HigherGenus/C/Aut/3.4-2.0.2-2-2-2-2-2.1

for example.

**Comment by AndrewVSutherland** [comment] 2018-05-24 20:09
I think this can be closed now, if anyone disagrees, please speak up.

**Comment by jenpaulhus** [comment] 2019-03-21 14:36
@AndrewVSutherland I think this can be closed now.

**Closed** 2019-03-21 14:37 UTC
Labels: hgcwa
