### ISSUE TITLE
Elliptic curve query times out

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#6058] opened 2024-05-19 14:01 UTC
From the feedback page:

I queried the LMFDB for the details of the elliptic curves with nonmaximal Galois image at the prime 37. They correspond to well-known exceptional points on the modular curve X_0(37), in that they are the only rational points on a curve X_0(p) of positive genus which do not correspond to CM elliptic curves. I was met with an error message: "Error: The search query took longer than expected! ". On the other hand, asking for the somewhat equivalent "isogeny class degree 37" caused no such issue.  

http://www.lmfdb.org/EllipticCurve/Q/?nonmax_primes=37

**Comment by AndrewVSutherland** [comment] 2024-05-19 15:29
This search is slow but not currently timing out, using exactly rather than includes is much faster (for this query doing this will yield the same results, but this is not true in general so this isn't a solution).

The problem is that the proportion of elliptic curves with non-maximal images at 37 is very small, and even with an index it takes time to find them when you are not doing an exact match. The situation here is analogous to searching by ramified primes in number fields. (there 37 is fine, but that's because lots of number fields in the LMFDB are ramified at 37, but try 1009 and it will time out).

**Comment by AndrewVSutherland** [comment] 2024-11-08 15:30
I don't think there is any action we can take here that is specific to ECQ.  Increasing the timeout (as suggested on #5970) would help, but other than that I don't think there is any obvious action we can take, so I'm going to close this issue.

**Closed by AndrewVSutherland** 2024-11-08 15:30 UTC
Labels: ECQ

**Comment by AndrewVSutherland** [comment] 2024-11-08 17:42
In fact the query is pretty snappy at the moment (under 2s), but I'm sure that is due in part to caching.
