### ISSUE TITLE
Genus 2 server error on search download

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1572] opened 2016-06-20 14:46 UTC
From Jen Balakrishnan via the feedback page:

"Clicking the magma/sage/pari links at the bottom of this page:
http://lmfdb.org/Genus2Curve/Q/?analytic_rank=0 (not just analytic rank 0, but also for any analytic rank query)

results in the following message:

The page you are looking for has produced a server error.
If you want to help improving the page behind ""http://lmfdb.org/Genus2Curve/Q/?analytic_rank=0"", please report that page's URL!"

Include @jbalakrishnan (and maybe directly jennifer.balakrishnan@gmail.com) in replies to this issue.

**Comment by AndrewVSutherland** [comment] 2016-06-20 15:35
I will fix this later today (I want to wrap up a PR I am working on now for Siegel modular forms first).

**Comment by AndrewVSutherland** [comment] 2016-06-22 13:18
Fixed by #1578

**Comment by AndrewVSutherland** [comment] 2016-06-22 13:18
And I'll e-mail Jen directly

**Comment by edgarcosta** [comment] 2018-04-03 11:08
@jbalakrishnan has reported the same issue again, and I have verified it

**Comment by AndrewVSutherland** [comment] 2018-04-03 12:55
@edgarcosta I just checked this and it works for me (using chrome on ubuntu), can you give more details on how you reproduced it?  I used the query http://www.lmfdb.org/Genus2Curve/Q/?analytic_rank=0&count=50 and clicking any of the magma, sage, pari buttons seems to work fine.

**Comment by JohnCremona** [comment] 2018-04-03 12:58
Same for me (also chrome ubuntu).  I'll try on a different machine in a while.

**Comment by jbalakrishnan** [comment] 2018-04-03 13:01
The issue for me (chrome on OS X) is that the downloaded file seems to be
all ~66,000 curves in the database, not the particular list of curves found
by the query.

Jen

**Comment by AndrewVSutherland** [comment] 2018-04-03 13:52
@jbalakrishnan Thanks, I get the same problem.

**Comment by edgarcosta** [comment] 2018-04-03 13:56
I also tested it in OSX with Chrome.

**Comment by AndrewVSutherland** [comment] 2018-04-03 16:04
Fixed by PR #2416.  As  @jbalakrishnan  indicated, the problem is not that the download buttons caused a server error, but that the download results contained all the curves in the database rather than the subset matching the query.  This has been fixed.

**Comment by jbalakrishnan** [comment] 2018-04-05 16:39
@AndrewVSutherland Thanks!

**Comment by edgarcosta** [comment] 2018-04-05 18:29
#2416 has been merged

**Closed by edgarcosta** 2018-04-05 18:29 UTC
Labels: genus2, production problem
