### ISSUE TITLE
Feature request: Search option "Bad primes of J(C)" for genus 2 curves/Q

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#4636] opened 2021-06-22 13:22 UTC
It would be great if one could search genus 2 curves/Q by the primes of bad reduction of their Jacobian (in analogy with the primes of bad reduction of C). The necessary data could be deduced from the already computed conductor.

**Comment by AndrewVSutherland** [comment] 2021-06-22 13:46
While I agree that this will be useful in the future, at present every genus 2 curve in the LMFDB has good reduction at every prime of good reduction for its Jacobian (it is very hard and likely impossible for a curve of discriminant < 10^6 to have bad reduction at  a prime of good reduction for its Jacobian, since that prime would have to be 2 and the conductor of the Jacobian would have to be very small, although there is a tiny window in which it could fit)  So you can effectively do this search now -- I'm just pointing this out for those who might find it useful to know this.

But when we add more genus 2 curves (which will happen in the not too distant future), this feature will be useful to have.  For example, the list of curves of 5-smooth discriminant at https://math.mit.edu/~drew/gce_genus2_hyperelliptic_5smooth.txt already contains more than a 1000 curves with bad reduction at primes where the Jacobian has good reduction, and this is just a subset of the curves we plan to add.

**Comment by bmatschke** [comment] 2021-06-22 14:51
That makes sense, thank you! (This also explains why there is no curve in the LMFDB whose Jacobian is only bad at 2 whereas the curve has more bad primes, which I was searching for.)

**Comment by roed314** [comment] 2024-11-15 07:30
Closing as a duplicate of #5667.

**Closed by roed314** 2024-11-15 07:30 UTC
Labels: feature request, Genus 2
