### ISSUE TITLE
Recursion error for elliptic curves

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5827] opened 2024-01-20 19:37 UTC
From the flasklog:
```
Exception on /EllipticCurve/Q/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/elliptic_curves/elliptic_curve.py", line 92, in rational_elliptic_curves
    return elliptic_curve_search(info)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/utils/search_wrapper.py", line 229, in __call__
    res = table.search(
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/searchtable.py", line 915, in search
    return self.search(
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/searchtable.py", line 915, in search
    return self.search(
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/searchtable.py", line 915, in search
    return self.search(
  [Previous line repeated 959 more times]
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/searchtable.py", line 894, in search
    cur = run_one_query(query, prelimit, offset)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/searchtable.py", line 820, in run_one_query
    return self._execute(
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/base.py", line 313, in _execute
    cur.execute(query, values)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/psycopg2/sql.py", line 122, in as_string
    rv.append(i.as_string(context))
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/psycopg2/sql.py", line 122, in as_string
    rv.append(i.as_string(context))
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/psycopg2/sql.py", line 122, in as_string
    rv.append(i.as_string(context))
  [Previous line repeated 2 more times]
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/psycopg2/sql.py", line 350, in as_string
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/psycopg2/sql.py", line 350, in <genexpr>
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
  File "/usr/lib/python3.10/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
RecursionError: maximum recursion depth exceeded while calling a Python object
[2024-01-20 18:12:41 UTC] 500 error on URL https://www.lmfdb.org/EllipticCurve/Q/?start=100050&discriminant=1&rank=1&showcol=ainvs.jinv
```

**Comment by JohnCremona** [comment] 2024-07-10 10:44
I just tried https://www.lmfdb.org/EllipticCurve/Q/?start=100050&discriminant=1&rank=1&showcol=ainvs.jinv and had no trouble.  It's an empty search as there no curves with discriminant 1.

Can we close this?

**Comment by AndrewVSutherland** [comment] 2024-07-10 10:48
I also cannot reproduce the problem, closing.

**Closed by AndrewVSutherland** 2024-07-10 10:48 UTC
Labels: ECQ
