### ISSUE TITLE
13525 non-cuspidal points

### ISSUE THREAD

**Issue by rbommel** [LMFDB/lmfdb#5938] opened 2024-03-13 15:12 UTC
On the [following page](https://beta.lmfdb.org/ModularCurve/Q/104.4.0-4.a.1.1/), it is claimed that 13525 non-cuspidal points have been stored for this curve (why?), but when clicking on it, you find none.

**Comment by roed314** [comment] 2024-03-14 04:14
This is a duplicate of #5678.  The points are stored because they come from elliptic curves over Q.

**Closed by roed314** 2024-03-14 04:14 UTC
Labels: Modular curves
