### ISSUE TITLE
Bianchi modular forms broken on postgres

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2620] opened 2018-08-30 22:56 UTC
The page <http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/?field_label=2.0.4.1> is broken under postgres due to trying to access fields which are not set, changing a v.pop() and a v['sfe'] to get(...) in `lmfdb/bianchi_modular_forms/bianchi_modular_form.py` fixes this quickly, but more care should be taken.

**Comment by JohnCremona** [comment] 2018-10-01 09:48
I think this reveals a data problem.  There are only 219 BMFs whose 'CM' field is not set, for example http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/377.1/a2/
and all are for field 2.0.4.1.  I cannot see any reason why they are not set as my raw data file has the CM field in all cases.  For that example see line 46 of  https://github.com/JohnCremona/bianchi-data/blob/master/newforms/newforms.1.1-10000  where the CM field is the 3rd after (16+11i) and has value 0 meaning "no CM".

**Comment by edgarcosta** [comment] 2018-10-01 18:06
I will look into it, as I started to look into this a month ago, but got sidetracked.
https://github.com/roed314/lmfdb_postgres/issues/86

**Comment by JohnCremona** [comment] 2018-11-12 10:04
This is still not fixed.

**Comment by roed314** [comment] 2018-11-12 10:46
How does one construct the label from the data file you pointed to?  The labels I'm seeing look like 2.0.4.1-2125.1-a2, but I only see the first two sections of that readily apparent in the data file.

**Comment by AndrewVSutherland** [comment] 2018-11-12 11:03
You could just pull this from mongo, the 221 CM forms listed here:

http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/?include_cm=only

Need to have the CM flag set to 1 in the postgres data.  But we should also check that nothing else is amiss.

**Comment by AndrewVSutherland** [comment] 2018-11-12 11:04
I can confirm that the 185360 forms without CM listed here:

http://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/?include_cm=exclude

do have the CM flag correctly set to 0 in the postgres data.

**Comment by AndrewVSutherland** [comment] 2018-11-12 11:30
What I wrote above about setting the CM flag to 1 (comment now delete) was wrong, it should be set to the discriminant of the CM field, which it is, except for the 219 records where the CM attribute is not set.

It looks to me like this is a problem with the data in mongo that simply got copied to postgres, not a problem that was created by the conversion (of course it still needs to be fixed).

**Comment by JohnCremona** [comment] 2018-11-12 11:31
I know what the problem is. All but 219 Bianchi newforms in the database have dimension=1 and the CM field correctly set to 0 or a negative discriminant, but there are 219 of dimension 2 for which no-one has determined the correct value of CM. So the website code just needs to take this into account.

I will fix this

**Comment by AndrewVSutherland** [comment] 2018-11-12 11:33
I also notice that the forms with CM by Q(i) have CM set to -1, should this perhaps be -4?

In either case, the CM knowl http://www.lmfdb.org/knowledge/show/mf.bianchi.cm should probably explain exactly what this number is.

**Comment by JohnCremona** [comment] 2018-11-12 11:46
Agreed about the knowl.  The data documentation (i.e. the inventory) does say "discriminant" so some values do indeed need to be multiplied by 4.  The code which computes these values takes square-free parts so that is what was uploaded.  We could either change the stored values (-1 to -4 etc) or change the display code to multiply by 4 when appropriate.  I'll do the latter anyway while I fix the other issue.

**Comment by JohnCremona** [comment] 2018-11-12 12:15
Same issue with the field 'sfe' (Sign of Functional Equation): not set for the 219 dimension 2 forms.
About CM values which are not 0 or 1 mod 4:  this is already handled correctly in the code, see the function cm_info() in bianchi_modular_form.py.   So the only issue is that the number stored is the square-free part and not the actual discriminant.  I think that is an issue for the inventory and associated coding/decoding functions and does not require any change in the database entries.

**Comment by JohnCremona** [comment] 2019-01-09 15:16
Can we close this?  The database issues have been fixed (as far as I can see).  The knowl does not yet define the CM discriminant, but that should be a different issue (nothing is now "broken").

**Comment by edgarcosta** [comment] 2019-01-09 15:56
I think so.

**Closed** 2019-01-09 16:56 UTC
Labels: BMF, critical
