### ISSUE TITLE
Number field search, set of ramified primes superset of is slow

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3227] opened 2019-08-11 21:26 UTC
On http://www.lmfdb.org/NumberField/ we can search fields by ramififed primes containing a given set, for instance http://www.lmfdb.org/NumberField/?ram_quantifier=include&ram_primes=2 but every such query I've tried has timed out, adding more restrictions on degree seems to help, but not always. Maybe some of these queries are cached so be sure to try this with different primes to see.

I appreciate there are a lot of number fields matching such a  query, but I wonder if this is a situation where adding indexes or whatever could help?

**Comment by edgarcosta** [comment] 2019-08-12 15:14
The root of the problem is the data type.
It should be an array of numerics instead of a jsonb, as indexes on jsonb do not support the superset operator, see https://www.postgresql.org/docs/current/gin-builtin-opclasses.html.

However, the fix isn't as easy as changing the data type, we already have a column `ramps_array`  with the right data type, but our current backend doesn't support searches on `numeric[]`, as PostgreSQL doesn't auto-cast integers to numeric.

```
 SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5] LIMIT 1;
ERROR:  operator does not exist: numeric[] <@ integer[]
LINE 1: SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5] LIMIT ...
                                                  ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

However,
```
SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5]::numeric[] LIMIT 1;
```
or
```
SELECT * FROM nf_fields WHERE ramps_array <@ '{5}' LIMIT 1;
``` 
works fine.


@roed314 and I are considering typecast every array, but we haven't gotten around to do it.

**Comment by roed314** [comment] 2019-08-15 09:18
I'm not sure that the data type is the true issue.  The following queries are executed on grace.mit.edu; the only difference is the LIMIT of 1 versus 100.

```
lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5]::numeric[] LIMIT 1;
                                                     QUERY PLAN                                                      
---------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..19.56 rows=1 width=363) (actual time=0.014..0.015 rows=1 loops=1)
   ->  Seq Scan on nf_fields  (cost=0.00..1263735.00 rows=64596 width=363) (actual time=0.013..0.013 rows=1 loops=1)
         Filter: (ramps_array <@ '{5}'::numeric[])
 Planning time: 0.829 ms
 Execution time: 0.063 ms
(5 rows)
```

```
lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5]::numeric[] LIMIT 100;
                                                                       QUERY PLAN                                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=1596.62..1913.33 rows=100 width=363) (actual time=400.733..5920.950 rows=16 loops=1)
   ->  Bitmap Heap Scan on nf_fields  (cost=1596.62..206182.11 rows=64596 width=363) (actual time=400.732..5920.943 rows=16 loops=1)
         Recheck Cond: (ramps_array <@ '{5}'::numeric[])
         Rows Removed by Index Recheck: 17793089
         Heap Blocks: exact=29914 lossy=888706
         ->  Bitmap Index Scan on nf_fields_ramps_array_gin  (cost=0.00..1580.47 rows=64596 width=0) (actual time=396.589..396.589 rows=5715206 loops=1)
               Index Cond: (ramps_array <@ '{5}'::numeric[])
 Planning time: 0.289 ms
 Execution time: 5921.000 ms
```

After changing the working memory, we get some improvement (in particular, we've eliminated the lossy heap blocks), but the query still takes 4 seconds.

```
lmfdb=> SET work_mem TO '64MB';
SET
lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5]::numeric[] LIMIT 100;
                                                                       QUERY PLAN                                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=1596.62..1913.33 rows=100 width=363) (actual time=730.873..3952.170 rows=16 loops=1)
   ->  Bitmap Heap Scan on nf_fields  (cost=1596.62..206182.11 rows=64596 width=363) (actual time=730.871..3952.162 rows=16 loops=1)
         Recheck Cond: (ramps_array <@ '{5}'::numeric[])
         Rows Removed by Index Recheck: 5715190
         Heap Blocks: exact=918620
         ->  Bitmap Index Scan on nf_fields_ramps_array_gin  (cost=0.00..1580.47 rows=64596 width=0) (actual time=533.706..533.706 rows=5715206 loops=1)
               Index Cond: (ramps_array <@ '{5}'::numeric[])
 Planning time: 0.327 ms
 Execution time: 3955.103 ms
```
and when we impose a sort order, we drop back to just using the degree/discriminant index:
```
lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps_array <@ ARRAY[5]::numeric[] ORDER BY degree, disc_abs, disc_sign, iso_number LIMIT 100;
                                                                                   QUERY PLAN                                                                                   
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..5296.13 rows=100 width=363) (actual time=0.031..6649.049 rows=16 loops=1)
   ->  Index Scan using nf_fields_degree_disc_abs_disc_sign_iso_number on nf_fields  (cost=0.56..3420726.98 rows=64596 width=363) (actual time=0.030..6649.043 rows=16 loops=1)
         Filter: (ramps_array <@ '{5}'::numeric[])
         Rows Removed by Filter: 19869427
 Planning time: 0.597 ms
 Execution time: 6649.095 ms
```

**Comment by edgarcosta** [comment] 2019-08-15 13:10
I'm extremely confused, but let's sort out a couple of things first.

1- My initial examples, with the operator '<@' were for subset operator.
This is still slow, as David points out.

2- The queries on superset are much faster with arrays (even without using index), by an order of magnitude.

Here are some times in ms


|`S`  |  array | jsonb | 
| - | - | - |
| `{2}`| 4.657 |  8627.056 | 
|`{5}`| 6.499 | 7942.891 |
|`{2,5}`|  19.244 | 6367.147 |

all obtained by doing 
```
EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps{_array} @> S ORDER BY degree, disc_abs, disc_sign, iso_number LIMIT 1000;
```
on grace.mit.edu.
I also did the array before the jsonb query, to give the cache advantage to the jsonb.

On proddb.lmfdb.xyz, the behaviour is similar, but the the jsonb times are much slower

|`S`  |  array | jsonb | 
| - | - | - |
| `{2}`| 3.599 | 59181.279 | 
|`{5}`| 5.845 | 15180.614|
|`{2,5}`|  13.190 | 60340.898 |

3- We should be do all the timings on proddb.lmfdb.xyz, as this is what serving www.lmfdb.org, and grace is a much better server than proddb.lmfdb.xyz will ever be when it comes to reading sequential data.

With that in mind, here are some timings for the subset operator

|`S`  |  array | jsonb | 
| - | - | - |
| `{2}`| 13213.357 | 5770.800 | 
|`{5}`| 6742.122 | 9405.184 |
|`{2,5}`| 10146.693 | 5934.202 |

which blows my mind, as both queries are using the same sequential scan.

**Comment by edgarcosta** [comment] 2019-08-20 16:35
We have now addressed the subset operator on beta.lmfdb.org

**Comment by AndrewVSutherland** [comment] 2019-08-20 18:14
Superset searches on beta are now crazy fast, which is great!  But I'm surprised that subset searches are still quite slow...

**Comment by AndrewVSutherland** [comment] 2019-08-20 18:31
@edgarcosta Sorry, this behavior is consistent with your table above so I should not be surprised.  It's still unfortunate that the subset queries are so slow (but at least they are fast enough to avoid timeouts).

**Comment by roed314** [comment] 2019-08-20 22:14
The issue is that we're still doing a glorified sequential scan, and we're just getting fortunate that there are a bunch of results with small degree so searches terminate quickly.  When there are fewer results, postgres uses a bitmap heap scan.

```
lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps <@ '{2,3}' ORDER BY degree, disc_abs, disc_sign, iso_number LIMIT 1000;
                                                                                    QUERY PLAN                                                                                     
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..8304.36 rows=1000 width=364) (actual time=0.016..8480.938 rows=1000 loops=1)
   ->  Index Scan using nf_fields_degree_disc_abs_disc_sign_iso_number on nf_fields  (cost=0.56..6812092.13 rows=820359 width=364) (actual time=0.014..8480.847 rows=1000 loops=1)
         Filter: (ramps <@ '{2,3}'::numeric[])
         Rows Removed by Filter: 14031226
 Planning time: 0.414 ms
 Execution time: 8481.070 ms

lmfdb=> EXPLAIN ANALYZE SELECT * FROM nf_fields WHERE ramps <@ '{101}' ORDER BY degree, disc_abs, disc_sign, iso_number LIMIT 1000;
                                                                    QUERY PLAN                                                                     
---------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=6280.26..6282.76 rows=1000 width=364) (actual time=1128.900..1128.902 rows=16 loops=1)
   ->  Sort  (cost=6280.26..6284.18 rows=1565 width=364) (actual time=1128.898..1128.899 rows=16 loops=1)
         Sort Key: degree, disc_abs, disc_sign, iso_number
         Sort Method: quicksort  Memory: 34kB
         ->  Bitmap Heap Scan on nf_fields  (cost=48.13..6197.22 rows=1565 width=364) (actual time=64.553..1128.768 rows=16 loops=1)
               Recheck Cond: (ramps <@ '{101}'::numeric[])
               Rows Removed by Index Recheck: 2195764
               Heap Blocks: exact=35607 lossy=102443
               ->  Bitmap Index Scan on nf_fields_ramps_gin  (cost=0.00..47.74 rows=1565 width=0) (actual time=52.546..52.546 rows=193653 loops=1)
                     Index Cond: (ramps <@ '{101}'::numeric[])
 Planning time: 0.722 ms
 Execution time: 1129.014 ms
```

The issue is the number of results (and the number with small degree).

```
lmfdb=> SELECT COUNT(*) FROM nf_fields WHERE ramps <@ '{101}';
 count 
-------
    16

lmfdb=> SELECT COUNT(*) FROM nf_fields WHERE ramps <@ '{2,3}';
 count 
-------
 49267

lmfdb=> SELECT COUNT(*) FROM nf_fields WHERE ramps <@ '{2,3}' AND degree = 2;
 count 
-------
     7
```

**Comment by roed314** [comment] 2019-08-20 22:15
I don't know how to fix this, since getting the query planner to choose a different strategy requires teaching it about non-uniform distribution of results....

**Comment by edgarcosta** [comment] 2019-08-20 22:20
We might have to play with:
https://www.postgresql.org/docs/current/runtime-config-query.html

for example, increase ` default_statistics_target` (the number of buckets
for the histogram) to 1000 or more.

**Comment by roed314** [comment] 2019-08-21 06:01
I don't think `default_statistics_target` will help us with this issue, since I think [increasing](https://dba.stackexchange.com/questions/200136/postgresql-what-the-default-statistics-target-value-really-means) it only means that more rows are sampled, not that rows are assumed to be anything other than independent.

**Comment by AndrewVSutherland** [comment] 2019-08-21 16:55
I just pushed the latest code to web, but superset searches are still very slow, for reasons I do not understand (I did restart both production web servers)

**Comment by edgarcosta** [comment] 2019-08-21 17:33
I don't think we will ever be able to convince Postgres that rows are not independent, but we can add correlation between columns
https://www.postgresql.org/docs/11/planner-stats-details.html

**Comment by AndrewVSutherland** [comment] 2019-08-22 00:46
The number fields database on web has now been updated to use arrays rather than jsonb (thanks Edgar!), and superset queries are now fast in www.lmfdb.org, sorry for the confusion.

Closing.

**Closed by AndrewVSutherland** 2019-08-22 00:46 UTC
Labels: backend, nf
