### ISSUE TITLE
L/Zeros/ModularForm/GL2/Q/holomorphic

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1232] opened 2016-05-08 05:17 UTC
Here are the tracebacks:

https://gist.github.com/edgarcosta/aab04be528490baeba3bb43c99494c95

Further, it still uses quite a lot of resources before quitting.

**Comment by jvoight** [comment] 2016-05-08 15:34
I think the issue is that the data is wrong, and so lcalc is going berserk.  I am not labeling this as critical because we know the classical modular forms are seriously broken, and so we should revisit this issue after.

**Comment by davidfarmer** [comment] 2016-05-09 20:28
This will be fixed when issue #439 is addressed.

I am working on a temporary solution.

**Comment by davidfarmer** [comment] 2016-05-09 23:32
closing because the temporary solution is adequate for now, and issue  #439 will fix properly

**Closed by davidfarmer** 2016-05-09 23:32 UTC
Labels: classicalMF, Lfcns, zeros
