### ISSUE TITLE
Higher rank elliptic curves

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#504] opened 2015-10-28 17:51 UTC
There are many other collections of elliptic curves which could be added.  The work this would involve includes:  preparing data produced by others into a standard format for upload; having a way to attach a code indicating which collection any one curve belongs to, for proper attribution; a page explaining which collections are included;  and for individual curves it will not be practical to include all the data which we currently have for every curve, so all the code needs to be adjusted to allow for incomplete data.  [Example: I started to add generators to the Stein-Watkins curves of prime conductors up to 10^10; for ranks>1 these had been found 10 years ago by myself (JEC), Watkins and Fisher, but I was using Heegner points to find the rank 1 generators.  However after 3 months running on 64 cores I was still only 3% though the list, at which point I moved on.]

**Comment by roed314** [comment] 2024-11-09 02:29
@JohnCremona: I think this is a duplicate of #963 and can be closed.

**Closed** 2024-11-09 09:58 UTC
Labels: ECQ, feature request
