### ISSUE TITLE
More coefficients in GL2 Maass form

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2576] opened 2018-08-18 18:00 UTC
In the "first" Maass cusp form with level 1 and R = 9.5...,
  http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032
I can only get 9 coefficients; but many more available in the L-function.  Where are they hiding?  Surely we should display more?

**Comment by edgarcosta** [comment] 2018-08-18 18:11
Yes, they are at least 100 of them (somewhere), as the L-functions for GL2 Maass forms are generated on the fly, and that is the threshold for us to generate the L-function

**Comment by AndrewVSutherland** [comment] 2019-05-28 20:11
The issue is that some forms have coefficients in mwf_forms, some have coefficients in mwf_coeffs, and some have both (this data was uploaded from different sources that used different conventions which likely also explains the 0/1 indexing shift noted in #2647).

So we know where the coefficients are hiding, we just need to figure out what combination of code/data changes will get them to be displayed on the screen.

**Comment by rbommel** [comment] 2019-11-15 19:54
Okay, I tried to do some research in the database to see what happened to the coefficients of http://www.lmfdb.xyz/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032. In the table where it gets its data from, _mwf_forms_, there are only 9 coefficients listed. So that is not the issue.

However, there seems to be a table _mwf_coeffs_ which contains raw data for coefficients as they were migrated from the old system. The problem is that its entries are listed by some label, which seems to be very hard to find for this particular Maass form.

I just went through the whole database to see where the coefficients are occurring and I found 6 candidate labels for this form:
c-1-0.0-1-1-9.5336952613
c-3-0-1-1-9.5336952613
c-5-0-0-1-9.5336952613
c-5-0-1-1-9.5336952613
c-9-0-0-1-9.5336952613
c-9-0-1-1-9.5336952613

Does anyone know which of these should be the right one? If we know this (in general of course, not just for this particular Maass form), then it should be possible to get more coefficients.

**Comment by davidfarmer** [comment] 2019-11-15 20:58
I have a guess at what the label notation means.  If that guess
is correct, then it is the first one that corresponds to the
Maass form on Gamma_0(1) that you linked.

And the others do not serve any useful purposes, because the
pages they correspond to no longer exist, because of these
closed issues:

https://github.com/LMFDB/lmfdb/issues/2688

https://github.com/LMFDB/lmfdb/issues/2645

Again assuming I understand the label notation, then the pattern
you will see in the labels is:

c-N1-something-decimal_number
c-N2-something-decimal_number
etc

The "something"s may be different, but the decimal numbers will
be the same.  The Ni are positive integers.

Now, if I also understand the errors that are happening,
then the there will be one Ni which is smaller than all
the others, *and* all the others will be multiples of
that smallest number.  It is the smallest one that you
want.

So, you might have

c-2-blah
c-6-blah
c-6-blah
c-10-blah.

In that case, the c-2-blah is the one you want.
Furthermore, on the home page of that Maass form the title
should mention \Gamma_0(2).

But you should not see

c-2-blah
c-6-blah
c-6-blah
c-7-blah.

because 7 is not a multiple of 2.

You should also not see the smallest Ni twice.

I think I have described a reasonably robust way to find what
you are looking for.

**Comment by edgarcosta** [comment] 2019-11-19 22:52
In case you want to compare with the old version
http://prod.lmfdb.xyz/ is back up
and the server m0.lmfdb.xyz if you want to connect to the DB directly

**Comment by AndrewVSutherland** [comment] 2019-11-20 01:02
@edgarcosta Thanks!

**Comment by AndrewVSutherland** [comment] 2019-12-13 21:59
Fixed via #3521

**Closed by AndrewVSutherland** 2019-12-13 21:59 UTC
Labels: Maass
