### ISSUE TITLE
Ecnf search results sets include_cm_curves and include_Q_curves to only by default

### ISSUE THREAD

**Issue by nmascot** [LMFDB/lmfdb#1250] opened 2016-05-09 12:56 UTC
For example, over 3.3.1016.1, there are curves of conductor norm 4 (as van be seen on /EllipticCurve/3.3.1016.1/), but searching for conductor norm 4 does not find them (it does not crash, it just finds nothing) : /EllipticCurve/3.3.1016.1/?start=0&count=50&field=3.3.1016.1&conductor_norm=4&include_isogenous=on&include_base_change=on&include_Q_curves=only&include_cm=only&torsion=&torsion_structure=&jinv=

**Comment by nmascot** [comment] 2016-05-09 13:02
Actually, even without the conductor norm condition, no curves are found : http://localhost:37777/EllipticCurve/3.3.1016.1/?start=0&count=50&field=3.3.1016.1&conductor_norm=&include_isogenous=on&include_base_change=on&include_Q_curves=only&include_cm=only&torsion=&torsion_structure=&jinv=

On the other hand, the curves over 3.3.49.1 are found.

**Comment by AndrewVSutherland** [comment] 2016-05-09 13:51
Search by conductor norm does work, see

http://www.lmfdb.org/EllipticCurve/3.3.1016.1/?start=0&count=50&field=3.3.1016.1&conductor_norm=4&include_isogenous=on&include_base_change=on&include_Q_curves=include&include_cm=include&torsion=&torsion_structure=&jinv=

The problem is that your query had include_Q_curves and include_cm set to "only".  I am looking into why this happened now.

**Comment by AndrewVSutherland** [comment] 2016-05-09 14:01
OK, problem identified (issue relabled accordingly).  Working on the easy fix now.

**Comment by JohnCremona** [comment] 2016-05-09 14:16
I'm awake and will look into this this morning PT.  It must be my fault.
John

**Comment by AndrewVSutherland** [comment] 2016-05-09 14:22
@JohnCremona The problem is in ecnf-search-results.html which sets both include_Q_curves and include_cm to "only" by default.  See lines 55-88.  I'm happy to leave it to you (but let me know if you want me to make the change).

**Comment by JohnCremona** [comment] 2016-05-09 15:00
I could, and probably should, since I wrote that.  I am looking at it know and will leave it to you since my logic after a 2-hour journey is clearly no better than it was when I wrote that code.

It is not a bug when manually entered URLs are messed up.  When I search for 3.3.1016.1, norm 4, I see results and also see the include/exclude boxes correctly set.  So I have not actually yet understood what the bug actually is.

**Comment by AndrewVSutherland** [comment] 2016-05-09 15:04
@JohnCremona No problem, I'll post a pull request shortly that you can review.

**Comment by AndrewVSutherland** [comment] 2016-05-09 16:31
Fixed in pull request #1251.

**Comment by AndrewVSutherland** [comment] 2016-05-09 16:32
Sorry, did not mean to close (clicked wrong button).  Close once merged and pushed.

**Closed** 2016-05-09 17:51 UTC
Labels: critical, ecnf

**Comment by AndrewVSutherland** [comment] 2016-05-09 18:24
@JohnCremona  Looks good, the page loads are now more than 10 times as fast as they were:

http://www.lmfdb.org/EllipticCurve/2.2.497.1/ : Connect: 0.026 TTFB: 0.121 Total time: 0.146
http://www.lmfdb.org/EllipticCurve/2.0.11.1/ : Connect: 0.026 TTFB: 0.273 Total time: 0.323
http://www.lmfdb.org/EllipticCurve/3.3.1957.1/ : Connect: 0.026 TTFB: 0.177 Total time: 0.227
http://www.lmfdb.org/EllipticCurve/4.4.19821.1/ : Connect: 0.027 TTFB: 0.214 Total time: 0.263
http://www.lmfdb.org/EllipticCurve/5.5.14641.1/ : Connect: 0.026 TTFB: 0.207 Total time: 0.257
http://www.lmfdb.org/EllipticCurve/6.6.371293.1/ : Connect: 0.027 TTFB: 0.217 Total time: 0.266
