### ISSUE TITLE
Tensor products of elliptic curves not working and/or extremely resource intensive.

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#500] opened 2015-10-28 17:40 UTC
If you choose to tensor product two elliptic curves, then select a random elliptic curve in each box and click on “tensor these”, you get a server error

http://beta.lmfdb.org/TensorProducts/show/?obj1=EllipticCurve%2FQ%2F272080%2Fl%2F2&obj2=EllipticCurve%2FQ%2F132800%2Fc%2F1

**Comment by JohnCremona** [comment] 2015-10-28 18:45
On 28 October 2015 at 13:40, Holly Swisher <notifications@github.com> wrote:

> If you choose to tensor product two elliptic curves, then select a random
> elliptic curve in each box and click on “tensor these”, you get a server
> error
>
>
> http://beta.lmfdb.org/TensorProducts/show/?obj1=EllipticCurve%2FQ%2F272080%2Fl%2F2&obj2=EllipticCurve%2FQ%2F132800%2Fc%2F1
>

The tensor product code is nowhere near powerful enough for this, which is
why we took it out of beta (or something).

**Comment by AndrewVSutherland** [comment] 2016-07-08 01:01
While in the process of cleaning up some of the L-function code I came across this and also cleaned up the tensor_products code and modified it to use the new error handling code introduced in PR #1667 so these internal server errors no longer occur and a more reasonable error message is displayed (in this case the issue is that current implementation requires both curves to be semistable).

It will at least attempt to compute tensor products of semistable elliptic curves, e.g. http://beta.lmfdb.org/TensorProducts/show/?obj1=EllipticCurve%2FQ%2F11%2Fa%2F2&obj2=EllipticCurve%2FQ%2F14%2Fa%2F1, but the computation is too expensive and it gets aborted after 30 seconds.

I'm not sure how feasible it is to compute these on the fly.  It would be a very cool feature to have but will require work to support efficiently.  I don't think a python computation on the fly is going to be fast enough, it will likely require some supporting pre-computation and/or C code.

**Comment by edgarcosta** [comment] 2016-07-08 01:22
Could we put a more reasonable time limit on it?
like in the case of the zeros or graph of an L-function?

**Comment by AndrewVSutherland** [comment] 2016-07-08 01:28
@edgarcosta How do we change the timeout for a specific computation?  I didn't realize one could do this.

**Comment by edgarcosta** [comment] 2016-07-08 01:29
I don't know at the moment.
I would need to look it up. My first approach would be to check the code of L-functions and zeros, to see how they do it.

**Comment by davidfarmer** [comment] 2016-07-08 01:47
Presumably we should precompute those tensor products, which will
probably go at the end of the list of other L-functions we are
planning to precompute.

**Comment by AndrewVSutherland** [comment] 2016-07-08 01:54
Precomputing is certainly the cleanest and most efficient solution, in which case all this code becomes obsolete.  But it would force us to impose a pretty low conductor bound, because otherwise there are just too many products to precompute. With some fast C code it might be possible to do this on the fly up to a much larger conductor bound.

But another advantage to precomputing is that we can then match automorphic friends via their Lhashes, which is not easy to do systematically otherwise, so maybe this is the best way to go.  Something to think about for Release 2.0.

**Comment by edgarcosta** [comment] 2016-07-08 02:21
Please ignore what I said.
I checked the Lfunction code, and it seems that they don't restrict the time, even though there is an argument for it:
https://github.com/LMFDB/lmfdb/blob/beta/lmfdb/lfunctions/Lfunction_base.py#L89

**Comment by JohnCremona** [comment] 2018-05-26 13:00
Since the tensor product code is not exposed even on beta (since 2015) can we close this issue?

**Comment by AndrewVSutherland** [comment] 2018-05-26 13:09
Agreed.

**Closed by AndrewVSutherland** 2018-05-26 13:09 UTC
Labels: Lfcns, feature request
