### ISSUE TITLE
Dirichlet group page display more characters

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4892] opened 2021-12-06 11:29 UTC
On the Dirichlet group page, e.g., https://beta.lmfdb.org/Character/Dirichlet/132/, which can reach via the bread of a character, we only display a limited number of characters without an option of seeing more.

**Comment by AndrewVSutherland** [comment] 2021-12-06 12:11
I think the table should also be changed to group  the characters into Galois orbits (sort on Galois orbit then character label).

**Comment by AndrewVSutherland** [comment] 2021-12-06 12:58
We should  also link  the group structure to the corresponding abstract  group.

**Comment by AndrewVSutherland** [comment] 2022-01-21 11:23
Duplicate of #3358.

**Closed** 2022-01-21 11:23 UTC
Labels: Dirichlet
