### ISSUE TITLE
Searching for curves with torsion

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3319] opened 2019-09-06 15:55 UTC
On the main page for Elliptic Curves ( /Elliptic ),
if I put 16 in the search box for Torsion order,
the resulting page has the 16 in the Isogeny degree field.

Also, I did not see any E/Q among the 117 curves it found.
(The first such example has conductor 210.)
Also, I could not guess the order in which the results were returned.

If I do the same search on the E/Q page ( /Elliptic/Q ),
then on the resulting page the 16 is in the Rank field.
(And searching again produces the same results, even though
it looks like I am now searching for Rank 16).

**Comment by AndrewVSutherland** [comment] 2019-09-06 16:00
This EC/Q torsion order 16 search works correctly on www.lmfdb.org so that part of the issue must be due to  very recent change (I'm pretty sure I know where the problem is, I will look at it shortly).

**Comment by JohnCremona** [comment] 2019-09-06 16:02
First quick point: the databases of curves over Q and over other fields are separate.  If you search from http://www.lmfdb.org/EllipticCurve/  you are not looking in the same table as if you search from http://www.lmfdb.org/EllipticCurve/Q/.  The only warning that this is the case is in the top line of http://www.lmfdb.org/EllipticCurve/ where it says (not including Q) somewhere.  Perhaps this should be made clearer.

The second thing is  fixable, as we just fixed a similar issue for EC/Q -- the 3rd oint above is OK on beta after that fix.

**Comment by AndrewVSutherland** [comment] 2019-09-06 16:17
Thanks @JohnCremona, you are right, the 3rd problem @davidfarmer noted is fixed on beta (via #3283) now that I have pushed the fix.

**Comment by JohnCremona** [comment] 2019-09-07 09:39
I would like to close this since I have no intention that searching on the top Elliptic Curves page should include curves over Q.  But it can be kept open pending a clearer indication that for results over Q a different search is needed.

**Comment by davidfarmer** [comment] 2019-09-07 19:16
It is a mixed signal that the first thing to browse on the top
Elliptic Curves page is curves over Q.  Probably that is why I
expected to see results from the search.

Maybe removing that is all that is needed?

**Comment by JohnCremona** [comment] 2019-09-07 19:56
Yes. I suggest deleting Q from the top of that browse list and instead add a sentence above that list saying something appropriate like 

This page is only for elliptic curves defined over number fields other than Q. Elliptic curves over Q have a dedicated set of pages.

With a link to the /Q page somewhere in there.

**Comment by davidfarmer** [comment] 2019-09-07 21:47
Good.  Then let's interpret that as the point of this issue.

**Comment by rbommel** [comment] 2019-11-01 19:27
I will change this.

**Closed** 2019-11-15 18:02 UTC
Labels: ec, ecnf, search
