### ISSUE TITLE
Igusa-Clebsch invariants not normalised for g2c

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4067] opened 2020-09-29 14:07 UTC
Apologies in advance if this is just me failing at reading comprehension but on https://www.lmfdb.org/Genus2Curve/Q/169/a/169/1 the Igusa-Clebsch invariants knowl says

>For genus 2 curves over $\Q$ we may assume that the Igusa-Clebsch invariants are integral. We can then normalize them by removing a factor of $d^k$ from $I_{2k}$, where $d$ is the largest positive integer for which the invariants remain integral after this normalization. In the LMFDB, Igusa-Clebsch invariants for genus 2 curves over $\Q$ are always normalized in this way

however I see:

<img width="295" alt="Screen Shot 2020-09-29 at 10 00 27" src="https://user-images.githubusercontent.com/1688533/94569060-49d5b380-023b-11eb-809b-5f1a7ac68842.png">

where I can factor out $2^1$ from $I_2$, $2^2$ from $I_4$, $2^3$ from $I_6$ and $2^5$ from $I_{10}$.

**Comment by AndrewVSutherland** [comment] 2020-09-29 14:42
@alexjbest You are right, this is a bug.  My guess is that the normalization was only removing d^2,d^4,d^6,d^10.  I will recompute these (and also check the normalization of the Igusa invariants, which may have the same issue).

**Comment by alexjbest** [comment] 2020-09-30 02:58
Thanks Drew! I was working within Sage which I don't think has G2 invariants unfortunately(?), but maybe it would be a nice easy Sage ticket to add those. Fortunately this was only for a small demo of how to look up a genus 2 curve, so I could work around it in this instance.

**Comment by AndrewVSutherland** [comment] 2020-10-01 14:56
This has been fixed on both beta and the production site.  The Igusa invariants were already normalized properly, but I added an additional normalization to make the first nonzero invariant I_2k with k odd positive by scaling by appropriate powers of -1 (I edited both the Igusa-Clebsch and Igusa invariant knowls to reflect this.  Adding this additional normalization ensures that no matter which projective weighted rational invariants you start with, after normalization you will always get the same list of integers.

**Comment by roed314** [comment] 2020-10-01 18:48
I'm getting a test failure on another PR.  I think you need to update `test_igusa_clebsch_search` (`lmfdb/genus2_curves/test_genus2_curves.py:222: AssertionError`)

**Comment by AndrewVSutherland** [comment] 2020-10-01 19:04
@roed314 Sorry about that, this should be fixed in #4073

**Comment by roed314** [comment] 2020-10-01 19:32
No problem!

**Comment by edgarcosta** [comment] 2020-10-08 19:47
We should have only factored squares, as the Igusa invariants live in P(2,4,6,10)

<img width="544" alt="Screen Shot 2020-10-08 at 15 44 35" src="https://user-images.githubusercontent.com/322822/95506002-43eb7b00-097d-11eb-9002-ff3ad479de5c.png">
p791 of  https://math.dartmouth.edu/~jvoight/quat-book.pdf

**Comment by AndrewVSutherland** [comment] 2020-10-08 20:19
True, but integers are squares in F^al = Qbar.  We are identifying Qbar-isomorphism classes, not Q-isomorphism classes.  

But In fact I was just following the [knowl](https://www.lmfdb.org/knowledge/show/g2c.igusa_invariants) written by Jeoren Sijsling.

If you can convince him that the knowl should be changed, I would be happy to renormalize them.  FWIW, I originally took your point of view, but after thinking about it I came around to Jeoren's.

**Comment by edgarcosta** [comment] 2020-10-08 21:38
Makes issue.

This issue arose on a call with Noam and @jvoight. Maybe they have something more to say.

Regardless, we should have some code that normalizes these invariants when we search on them.
Furthermore, shouldn't we also normalize the sign so that the first invariant is always positive?

**Comment by AndrewVSutherland** [comment] 2020-10-08 22:32
They should be normalized so that the sign of the lowest weight nonzero invariant is positive, can you give me an example where they are not?

**Comment by edgarcosta** [comment] 2020-10-08 22:47
They are, as far as I can tell, but from the knowl it is not clear.
Anyhow, closing the issue, as you addressed my confusion

**Comment by AndrewVSutherland** [comment] 2020-10-08 22:52
@edgarcosta I think the [knowl](https://beta.lmfdb.org/knowledge/show/g2c.igusa_invariants) is clear on the sign convention (I updated it when I renormalized the invariants).  But let me know if you disagree (perhaps you were only looking at www.lmfdb.org and were not looking at the most up to date version of the knowl, which is awaiting review).

**Comment by AndrewVSutherland** [comment] 2020-10-08 22:56
In fact the knowl is clearer than what I wrote above (we can make a nonzero I_{2k}  positive when k is odd, but not when k is even).

**Comment by edgarcosta** [comment] 2020-10-08 23:11
Yup, that was my mistake of checking www.lmfdb.org.

**Comment by jvoight** [comment] 2020-10-08 23:50
If we're going to do this, we have to say in the knowl that "they are equivalent as points in a weighted projective space **over the algebraic closure of QQ**.  They are not equivalent as points of PP(2,4,6,10)(QQ).  

This is very analogous to consider the c_4 and c_6 of an elliptic curve.  On the QQ-isomorphism class, we have something well defined up to 4th, 6th powers of rational numbers.  (Geometrically, this becomes 4th, 6th powers of algebraic numbers, etc.).  Are you sure this is a good convention?  In effect, by this choice we are deciding to losing information about the QQ-isomorphism (twist) class.  

I would have identified the typo in the knowl as being "d^{2k} from I_{2k}".  

[In my book, I only consider objects over algebraically closed fields, so it is not the best reference for this particular situation--but it does claim to let you see the effect of a change of variables over any field.]

**Comment by AndrewVSutherland** [comment] 2020-10-09 00:06
@jvoight I edited the knowls as you suggested. I'm not sure what you mean about the typo, are you saying you thought it was a typo or that there is a typo?  I think the d^k is intentional (it appears in both the Igusa invariant knowl and the Igusa-Clebsch knowl), but you would really need to check with Jeoren to be sure.

I don't have a strong opinion on this (but I'm guessing that Jeoren does). I'm happy to do whatever you and Jeroen think is best.

As I said above, I actually started out agreeing with Edgar and then changed my mind when I realized the Igusa/Igusa-Clebsch invariants only ever tell you anything about the geometric isomorphism class (and the field of moduli), I don't think normalizing them up to factors of d^{2k} versus d^k provides any additional information.

In particular, I don't think this is similar to c4, c6, because c4, c6 uniquely determine a Q-isomorphism class, and this information would be lost if you normalized by d^2 and d^3 rather than d^4 and d^6.

**Comment by jvoight** [comment] 2020-10-09 01:03
Thanks!  

By "typo", I meant to answer Alex's original point.  

I invited Jeroen to comment here, we should be able to decide this by mathematical considerations.  Can you help me to see where I'm wrong?  A general isomorphism of curves is given by (43.3.3) in my book, and it has the effect described by the equivalence relation I_{2k} ~ delta * I_{2k}.  So I think we have something well-defined this way on the QQ-isomorphism class.  Happy to be wrong, but would like to know why!

**Comment by AndrewVSutherland** [comment] 2020-10-09 08:47
@jvoight Hmm, I don't think they give a well-defined QQ-isomorphism class.  Consider,. for example,
```
> C1:=HyperellipticCurve(x^5-x+1);
> IgusaInvariants(C1);            
[ -80, 480, 1280, -83200, 734464 ]
> C2:=HyperellipticCurve(-x^5+x-1);
> IgusaInvariants(C2);             
[ -80, 480, 1280, -83200, 734464 ]
> IsIsomorphic(C1,C2);
false
```
Even without normalizing anything, Magma returns exactly the same Igusa invariants for these distinct QQ-isomorphism classes (of course Magma has been known to be wrong, but these look right to me).

More generally, I think you are going to get equivalent QQ-points in weighted projective space whenever you take a quadratic twist, but these correspond to infinitely many distinct QQ-isomorphism classes of genus 2 curves.

**Comment by AndrewVSutherland** [comment] 2020-10-09 09:27
@jvoight I think the issue is that the argument you give following 43.3.3 proves that the equivalence relation is stable under Q-isomorphism, so there is a well-defined map from the set of Q-isomorphism classes to the set of equivalence classes of Q-points in weighted projective space, but it does not imply that this map is injective.  In particular, Proposition 43.3.7 is false if you replace F^al with F (but of course you don't do that, everything you wrote is fine).

**Comment by jvoight** [comment] 2020-10-09 15:01
@AndrewVSutherland In case anyone else is reading this and comparing to the LMFDB, I think you want to take IgusaClebschInvariants(C1) in the above (we want 4 numbers, not 5 numbers) to match our defaults--but that doesn't change your conclusion. 

It's in the factor c, thanks!  This is visible in the definition of the invariants.  

I'm still happy with whatever is decided here, but my instinct remains to keep information instead of throwing it away.  For example, if we kept track of the leading coefficient, or the oft forgotten I_{15}-invariant (which is algebraically dependent on the others), we would have something well-defined on the QQ-isomorphism class (the map is now injective, not just well-defined).

To put it a different way: if Igusa invariants are like the j-invariant of an elliptic curve, then I think we should be taking rescaled ratios (e.g. G2-invariants).  We get three rational numbers, and you instantly detect the QQbar-isomorphism class.  It's of course still well-defined to take elements of PP(2,4,6,10)(QQbar) with a representative in PP(2,4,6,10)(QQ) and then to pick out a unique representative with this property.

**Comment by JRSijsling** [comment] 2020-10-09 15:21
Hello! I do not remember what I thought before, but I would have taken this into account. I would still be inclined to normalize by (1,2,3,5) since this is geometric. That does throw stuff away, but there is this counterexample, and besides, why use the invariants otherwise? There are no duplicates in the LMFDB. The nice thing about normalizing geometrically is that it gives you some information about potential good reduction.

**Comment by jvoight** [comment] 2020-10-09 19:49
OK, if the bugs are fixed, I think we should close this issue.  The decision is a mathematically correct one.  

I still think we have created an inconsistency between g = 1 and g = 2 with this choice, and I don't think it matches a "functor of points"  view of the stack... but such comments don't belong in a github thread.

On that note, Jeroen, I'd appreciate it if you'd follow up with me by email about your comment on potential good reduction.  (I think this information is only partial, unless you consider representatives of PP(2,4,6,10)(QQbar) outside of QQ.)

**Comment by AndrewVSutherland** [comment] 2020-10-09 21:29
Thanks @JRSijsling and @jvoight for settling this.  I'm going to close it now (this issue was reopened only because there was some debate about whether the normalization we are using is correct/desirable, I made the one clarification to the knowls that was suggested and I don't think there is anything else that needs to be done).

**Closed by AndrewVSutherland** 2020-10-09 21:29 UTC
Labels: Genus 2
