### ISSUE TITLE
Should be able to have single Dirichlet characters 

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#863] opened 2016-03-27 11:29 UTC
It looks like the right way to create a single Dirichlet Character is with 

  WebDirichletCharacter(modulus=5, number=2)

If you have a gigantic modulus, this crashes the site with sage having a segfault.  I think this is because when creating a single character, the entire set of characters with the given modulus.  It works now when the modulus is small, but I want to use it when the modulus is very large (to use the methods for displaying the character, and then we want to be able to display the page for the one character.

**Comment by pascalmolin** [comment] 2016-03-27 16:35
I am handling this one.
(the reason is the one you point to, normally the WebDirichletCharacter was designed precisely to avoid calling sage dirichlet group -- which stores all group elements -- except for specific operations like computing gauss and jacobi sums and I remember writing tests on large moduli precisely to ensure that, but it was 3 years ago and things may have shift the wrong way).

**Comment by JohnCremona** [comment] 2016-03-30 13:26
Fixed by #905

**Closed by JohnCremona** 2016-03-30 13:26 UTC
Labels: April
