### ISSUE TITLE
Some HMFs are missing Atkin-Lehner eigenvalues

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2228] opened 2017-08-16 20:02 UTC
When Hilbert Modular Forms were first uploaded, some (possibly all) had no AL-eigenvalues and these were added later.  This jobs is not exactly complete, as the following shows (where forms is the collection hmfs.forms):

sage: forms.distinct('AL_eigenvalues_fixed')
[u'done', u'working', True, u'MISSING\n', u'done\n', u'MISSING', u'working\n']
sage: forms.count({'AL_eigenvalues_fixed':'MISSING'})
375
sage: forms.count({'AL_eigenvalues_fixed':'MISSING\n'})
146
sage: forms.count({'AL_eigenvalues_fixed':'working\n'})
4
sage: forms.count({'AL_eigenvalues_fixed':'working'})
7624
sage: forms.count({'AL_eigenvalues_fixed':True})
37
sage: forms.count({'AL_eigenvalues_fixed':'done'})
354192
sage: forms.count({'AL_eigenvalues_fixed':'done\n'})
2091

The code to display one HMF checks whether the field's value is 'done'
and displays '?' if not.  All those with 'done\n', 'working',
'working\n', True should have the field changed to 'done' I expect.
Better would be to fix the remaining 375+146 !

**Comment by jvoight** [comment] 2017-08-18 17:45
This is a duplicate of #420.

**Closed** 2017-08-18 18:23 UTC
Labels: HMF
