### ISSUE TITLE
Elliptic curves over number fields: randomizer link is not obviously clickable

### ISSUE THREAD

**Issue by TylerGenao** [LMFDB/lmfdb#3351] opened 2019-09-10 14:42 UTC
The "random elliptic curve" link on the main page for elliptic curves over number fields is nearly indistinguishable from the rest of the sentence, so it almost seems unclickable. The whole sentence is close to being the same blue color.

**Comment by JohnCremona** [comment] 2019-09-10 15:05
Duplicate of #3336 and already fixed (but note yet on beta).

**Closed by JohnCremona** 2019-09-10 15:05 UTC
Labels: ecnf, good first issue
