### ISSUE TITLE
Maass form download not working correctly

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2950] opened 2019-04-11 02:42 UTC
UPDATE: the original problem has been fixed, but there still is an issue in that you can only download a few of the 5000 coefficients we have stored for most forms.

From the feedback page:

=====================
Only one of the Maass forms of level 1 has any coefficients??

Alas, I needed one of even symmetry...

http://www.lmfdb.org/ModularForm/GL2/Q/Maass/

======================

There was no name or contact e-mail.

Note, the search results page says all but 1 have no coefficients, but if you go to the individual pages, they seem to have a few.

**Comment by edgarcosta** [comment] 2019-04-11 16:17
1- I think if the collumn Numc is null, then we should say 5000 instead of 0
2- We can't download all the 5000 coefficients, as we could before: http://prod.lmfdb.xyz/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032

**Comment by edgarcosta** [comment] 2019-04-11 19:15
This might be a data conversion issue from MongoDB to PostgreSQL:
http://prod.lmfdb.xyz/api/MaassWaveForms/FS/?Level=i1
vs
http://beta.lmfdb.org/api/mwf_forms/?Level=1

**Comment by edgarcosta** [comment] 2019-04-11 19:37
We fixed the data issue.

Not the download issue.

**Comment by edgarcosta** [comment] 2019-04-11 19:58
ps: this was only an issue at level 1

**Comment by AndrewVSutherland** [comment] 2019-04-11 20:35
It looks like the data issue that caused the original problem is now fixed on beta.  @edgarcosta should we copy the modified mwf tables over to proddb (which would fix the original problem) or do you anticipate that fixing the download problem might also involve data changes?

**Comment by edgarcosta** [comment] 2019-04-11 20:36
Can I just edit the data directly on proddb?
We just did:
```
UPDATE mwf_forms SET "Numc" = 5000 WHERE "Numc" is Null;
```
note, that `Numc` was only `Null` for level 1, and in those cases was supposed to be 5000

**Comment by AndrewVSutherland** [comment] 2019-04-11 20:59
I think this is safe (and the file is small), go ahead.

**Comment by edgarcosta** [comment] 2019-04-11 21:25
Done

**Comment by AndrewVSutherland** [comment] 2019-04-11 21:36
@edgarcosta Thanks, I have removed the critical label since the originally reported problem is fixed.  I'll leave the issue open for the purpose of fixing downloads.   @jwj61 if you have an e-mail address, can you let whoever posted the issue know that it has been fixed.

**Comment by edgarcosta** [comment] 2019-04-12 19:48
@AndrewVSutherland is this still a 1.1 thing?

**Comment by AndrewVSutherland** [comment] 2019-04-12 21:28
@edgarcosta I don't think this is necessary for 1.1 so I have removed the 1.1 milestone, but it would be nice to have if the fix is easy.

**Comment by rbommel** [comment] 2019-11-08 21:42
Could anyone explain this issue a bit more detailed? If I go to https://www.lmfdb.org/ModularForm/GL2/Q/Maass/54104e8aacf756699fe08307?download=coefficients it seems that I can download a lot of coefficients.

**Comment by AndrewVSutherland** [comment] 2019-11-08 22:06
@rbommel The issue is that if you look at

http://www.lmfdb.xyz/ModularForm/GL2/Q/Maass/1/

you will see that we claim to have 5000 coefficients for all the listed forms, but if you go to the forms home page and download coefficients, you only see the first few, e.g.

http://www.lmfdb.xyz/ModularForm/GL2/Q/Maass/4cb8503a58bca91458000032

and if you download all coefficients, these are still the only ones you see.

In the mongo db version we did have 5000 coefficients for these (although you cannot see that right now because prod.lmfdb.xyz is no longer available, is that correct @edgarcosta?)   I believe the issue is due to the fact that there are two different ways maass form coefficients were stored (some were stored in json, which is the case for the example you gave, as you can see at https://www.lmfdb.org/api/mwf_forms/?maass_id=54104e8aacf756699fe08307), but others were stored as binary data in the mwf_coeffs collection (https://www.lmfdb.org/api/mwf_coeffs/).

You could check with @roed314, but I believe the binary data was ported to postgres, but for some reason the code is not accessing it correctly.

In the long term we are planning to recompute all of this data and store it in a single consistent format.  In the short term we need to either (1) figure out what went wrong in the conversion of the binary data from mongo to postgres and/or figure out how to get the code (which is a bit of a spaghetti-fest) to read the data from postgres correctly, or (2) we need to change the browse table to only show the number of coefficients that we are actually able to pull out of the database.

(1) would be preferable, and it could be a trivial fix, or it could be a major pain and/or require reconverting the data from mongo -- the only way to know is to dig into it.  For anyone who is motivated/willing to do so, my suggestion would be to expend a bounded amount of effort trying to achieve (1) and after that just say "no maass" and implement (2) as a stopgap until the new Masssform data is available.

**Comment by edgarcosta** [comment] 2019-11-11 18:34
- Yes, the servers were shutdown but I can start them again.

- Even the form https://www.lmfdb.org/ModularForm/GL2/Q/Maass/54104e8aacf756699fe08307 is confusing, as we display 500 coefficients but can download more ~1200, and when you look at https://www.lmfdb.org/ModularForm/GL2/Q/Maass/2/ is one of the many forms for which we say that we have 0 coefficients.

**Comment by AndrewVSutherland** [comment] 2019-11-15 18:34
@edgarcosta Can you restart prod.lmfdb.xyz when you get a chance?  It would be helpful to be able to compare.

**Comment by edgarcosta** [comment] 2019-11-19 22:51
http://prod.lmfdb.xyz/ is back up
and the server m0.lmfdb.xyz if you want to connect to the DB directly

**Comment by AndrewVSutherland** [comment] 2019-12-13 21:57
Fixed via #3521

**Closed by AndrewVSutherland** 2019-12-13 21:57 UTC
Labels: Maass, production issue
