### ISSUE TITLE
crash when trying to display search results for HMFs

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#616] opened 2015-11-25 18:29 UTC
If you search for many HMFs, as in 
http://beta.lmfdb.org/ModularForm/GL2/TotallyReal/?start=1000&field_label=4.4.2000.1&field_degree=&field_disc=&weight=&level_norm=&dimension=&count=100,
and click on 'next' to get to the next page, everything works fine for the first few pages, and then the page crashes (when trying to get from the first 1001-1100 matches to the first 1101-1200 matches in the example above).

Same problem if you directly try to display a large number of them, as in
http://localhost:37777/ModularForm/GL2/TotallyReal/?field_label=4.4.2000.1&field_degree=&field_disc=&weight=&level_norm=&dimension=&count=1200

**Comment by jvoight** [comment] 2016-02-06 20:41
Probably related: when you search for HMFs with a start value, as in 
  http://www.lmfdb.org/ModularForm/GL2/TotallyReal/?start=100&field_label=2.2.5.1&field_degree=&field_disc=&weight=&level_norm=500&dimension=&count=100
or when you refine a search, it also crashes.

**Comment by JohnCremona** [comment] 2016-02-07 16:54
I assigned this to myself since I think I wrote the next/previous feature here.

**Comment by kedlaya** [comment] 2016-02-08 15:35
Possibly also related: the "random" search times out. (If this turns out not to be related, please split it off into a separate issue.)

**Comment by JohnCremona** [comment] 2016-02-09 09:23
I have tracked this down.  If you do a search on a collection C like res = C.find(...) then you can see how many objects were found uding res.count().  If you have used skip or limit, for example res = C.find(...).limit(100) then you might think that res.count() will return 100, possibly pess, but that is not the case!  It returns the length of the full iterator, unless you do res.count(with_limit_and_skip=True).

In the HMF case we were using res.count() to check that the iterator was not empty and then accessing res[0].  This caused an error when the sub-iterator was empty while the full one  was not.
I have corrected this in the HMF code but will now go through all other places where this sort of thing is used in case it happens anywhere else.

**Comment by JohnCremona** [comment] 2016-02-09 09:35
None of the other palces were a problem; in fact only one place actually counts the number of results after applying the filters (Maass forms) and that did it properly.

The random HMF is something else -- for me it is very fast on www, beta and local.  Kiran, can you confirm?  It might have been some one-off thing?

**Comment by JohnCremona** [comment] 2016-02-09 10:05
Continuing to test -- while what I found above really was a bug, the second thing which Aurel reported is still a problem.  Start with looking at all HMFs for 4.4.725.1, which has 5361 hits, and keep clicking on "Next".  It's fine for about 10 times, "displaying matches 1101-1200 of 5361" but one more Next and it crashed with the error message

"OperationFailure: database error: Executor error: OperationFailed Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."

But the traceback shows that the error is only triggered when res[0] is accessed.  So I realised that the thing being set by reference to res[0] was not used, so removed that code.  The problem still persists:  after about 10 clicks on Next we get the error above as soon as the iterator res is used.

The exact same kind of code is used in othe rp[alces with Previous / Next buttins, e.g. elliptic curves over Q, but these give no problems.  Why?  Since it is doing some sorting I guess that what we need on HMFs is an idex on precisely the same sort criteria as used in creating the offending iterator:
[('deg', pymongo.ASCENDING), ('disc', pymongo.ASCENDING), ('level_norm', pymongo.ASCENDING), ('level_label', pymongo.ASCENDING), ('label_nsuffix', pymongo.ASCENDING)]
I will create such an index and see if that helps.

**Comment by JohnCremona** [comment] 2016-02-09 10:21
OK, so creating an index solves the problem.  No code change needed, so I will close the issue, but I did delete 4 redundant lines of code and will get that merged separately.
If someone else checks that the problems originall reported have gone away we can close this.
NB See also tha annotation I made to JV's comment above.

**Comment by kedlaya** [comment] 2016-02-09 15:14
The "random" search crash was reproducible when I reported it (that it, I tried several times and it kept happening), but seems to be fine now, even on production. If it comes up again, I'll raise a separate issue, but let's call it a one-off for now.

**Comment by JohnCremona** [comment] 2016-02-09 16:38
OK, thanks.

**Closed** 2016-02-09 16:37 UTC
Labels: HMF
