### ISSUE TITLE
Sage/Magma generation commands for modular forms

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#1346] opened 2016-05-13 23:38 UTC
It was observed here:

https://galoisrepresentations.wordpress.com/2016/05/12/lmfdb/#comments

that we don't currently provide Sage/Magma code to create modular forms.

**Comment by JohnCremona** [comment] 2016-05-13 23:56
Duplicate of #1334

**Closed by JohnCremona** 2016-05-13 23:56 UTC
