### ISSUE TITLE
Genus 2 endomorphism display

### ISSUE THREAD

**Issue by JRSijsling** [LMFDB/lmfdb#1093] opened 2016-04-27 17:55 UTC
If one goes to the page of a genus 2 curve, like

http://www.lmfdb.org/Genus2Curve/Q/169/a/169/1

then the endomorphism information of this curve is displayed; upon scrolling down, we see nice rings and algebras. Now we can scroll up and change the chosen invariants by clicking "Igusa" or "G2". We get new invariants. But if we scroll down, then only the skeleton of the endomorphism information remains, in the sense that only the surrounding statements are left. The meat, that is, all relevant lines on endomorphism rings and algebras, has gone.

This is somewhere in lmfdb/genus2_curves/templates/curve_g2.html. I know that since I coded the current invariant display (search for invstyle in that file to see where it comes from). I just do not know how to fix it... any help would be tremendously appreciated.

**Comment by JohnCremona** [comment] 2016-04-28 13:10
Very strange.  I am looking at it now.

**Comment by JohnCremona** [comment] 2016-04-28 13:21
Looking at line 210 in that html file: there are three items, the second of which has a double level of <span>...</span>  Why?  Is it that Igusa-Clebsch is the default?
Also one of these items have nodisplay in the class= lists (the first) but not the others.  Why?
I am just trying to understand the logic.

**Comment by JRSijsling** [comment] 2016-04-28 14:40
Your remarks are very correct. I wish that I understood the logic. The problem is that I took some of the similar code used for showing Magma and Sage code and hit that over the head until it worked. I may be able to hit it back into shape, but since I understand too little of this environment and since this is exactly how the current bug came to be, that seems like asking for trouble at some point further down the line. Perhaps someone who designed the code for showing Magma and Sage code will know a way out of this.

The nodisplay and the double level for Igusa-Clebsch are indeed both there because those are the default.

**Comment by AndrewVSutherland** [comment] 2016-04-28 14:52
I figured out how to fix this -- the problem is a name conflict (g2 is used for two different things).  I'll push the fix shortly.

**Comment by JRSijsling** [comment] 2016-04-28 14:53
Thanks Drew, that is great!

**Comment by JohnCremona** [comment] 2016-04-28 14:54
You win a prize!  Thanks

**Comment by AndrewVSutherland** [comment] 2016-04-28 15:07
Fixed in pull request #1102

**Closed** 2016-04-28 15:59 UTC
