### ISSUE TITLE
Precision of special L-values of elliptic curves/Q

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#4564] opened 2021-05-08 13:44 UTC
Some special L-values of elliptic curves/Q seem to have several false digits at the end, e.g. https://www.lmfdb.org/EllipticCurve/Q/37a1 currently lists
0.30599977383405230182048368332169132525,
whereas sage's E.lseries().taylor_series() using large precision gives:
0.305999773834052301820483683321676474452637774590771998534541832481016050469290169911495257337795897...
I don't know how numerically stable the latter is, I simply increased precision until the first 100 digits seem to stabilize.

**Comment by edgarcosta** [comment] 2021-05-08 14:06
from https://beta.lmfdb.org/api/ec_mwbsd/?lmfdb_label=37.a1 we see that the 
the value stored is 
`0.30599977383405230182048368332169132525`
while the correct value is
`0.305999773834052301820483683321676474452637774590772?`

**Comment by JohnCremona** [comment] 2021-05-08 14:53
This must be my fault since I recently recomputed all these values using libpari from Sage like this:
`ar, sv = E.pari_curve().ellanalyticrank(precision=PRECISION).sage()`
with PRECISION=100, for example
`sage: E = EllipticCurve('37a1') `                                                                                                                      
`sage: E.pari_curve().ellanalyticrank(precision=100).sage() `                                                                                           
`[1, 0.30599977383405230182048368332169132525]`
while in gp itself we see
`? ellanalyticrank(ellinit("37a1"))`
`%4 = [1, 0.30599977383405230182048368332167647445]`
So something is going wrong in converting the real number from libpari to Sage.

Someone will need to work out why this happens;  submit a bugfix to Sage if it is a Sage issue; and in any case recompute all these values and re-upload them.  That person will not be me any time soon!

**Comment by bmatschke** [comment] 2021-05-08 15:39
Thanks, I didn't know about this bug. Similarly:
    
    sage: gp.set_real_precision(100)
    38
    sage: a = gp.sqrt(2)
    sage: a
    1.414213562373095048801688724209698078569671875376948073176679737990732478462107038850387534327641573
    sage: a.sage()
    1.414213562373095048801688724209698078569671875376948073176679737990732478462107038850387534327641573000000000000000

**Comment by JohnCremona** [comment] 2021-05-08 15:51
Sone of the reason for what you observe is that pari bit precision goes up in jumps of 32 or 64 while sage allows any bit precision.  This is supposed to be handled properly in the interface.

**Comment by bmatschke** [comment] 2021-05-08 17:05
Then maybe it's not even a bug. There are two opposite goals in such a conversion: 

1. Preserve all known binary digits.
2. Preserve that numbers stay correct up to 1 ulp. 

And it seems that sage chose 1.).

**Comment by JohnCremona** [comment] 2021-05-08 18:21
In the short term we could easily truncate the display pending changes to the stored numbers.

**Comment by JohnCremona** [comment] 2022-01-21 13:22
I will look into this today

**Comment by JohnCremona** [comment] 2022-01-21 14:21
I was right that this is caused by the Sage/libpari interface, which does not properly handle the fact that pari's bit precision can only be adjusted in jumps of 32 or 64.  If you look at the following in Sage:

sage: E = EllipticCurve('37a1')                                                                                                         
sage: E.pari_curve().ellanalyticrank(precision=100)[1].sage()                                                                           
0.30599977383405230182048368332169132525
sage: E.pari_curve().ellanalyticrank(precision=100)[1].sage().parent()                                                                  
Real Field with 128 bits of precision

sage: E.pari_curve().ellanalyticrank(precision=128)[1].sage()                                                                           
0.30599977383405230182048368332167647445
sage: E.pari_curve().ellanalyticrank(precision=150)[1].sage()                                                                           
0.305999773834052301820483683321676474452637768360086942368
sage: RealField(128)(1+2^-100)                                                                                                          
1.0000000000000000000000000000007888609

you can see that when you ask for 100 bits precision -- which is what I computed all these numbers at -- the number you get after converting back to Sage has 30 correct digits (30 digits=100 bits roughly) which would be in this example 0.305999773834052301820483683321, plus some incorrect digits since the converted value has parent RealField(128) not RealField(100).

I can fix this in the LMFDB code by coercing all the real number values into RealField(100) before they are displayed.  I'll need to do this for EC/Q and EC/NF.  For the future I will fix my sage scripts which compute the numbers to do this already.  None of this would have happened if I had chosen to copute everything to 128 bits instead of 100!

**Comment by roed314** [comment] 2022-01-21 17:33
Do you know if there is an issue about this on trac.sagemath.org?  It's worth reporting there as well.

**Comment by JohnCremona** [comment] 2022-01-21 19:56
> Do you know if there is an issue about this on trac.sagemath.org? It's worth reporting there as well.

I will.

**Comment by bmatschke** [comment] 2022-01-21 20:06
Before reviewing it, I would need to understand what the claimed precision is: I think it's impossible to claim that displayed numbers are truncated, and neither that they are rounded (see https://github.com/LMFDB/lmfdb/issues/2632#issuecomment-1018788658). So in my opinion, one should aim correctness up to 1 ulp.
The raw data in ec_mwbsd is given decimally -- is it provably correct up to 1 ulp?
The code in the PR is first coercing the raw decimal number to RealField(100) and then to a string. I'm not sure how the latter conversion works in Sage. 
Perhaps it's better to just take the raw string and take the first, say, 30 digits, though one has to take care if scientific notation is used or if the decimal point comes after the first 30 digits.

**Comment by JohnCremona** [comment] 2022-01-22 13:09
I thought I had explained this above.  The data is uploaded from a file where obviously it is a string (with some extra incorrect digits right now).  No computations are done with these numbers before displaying so it would be possible to use a a 'string' data type in the database instead of the 'numeric' data type.  Right now the only drawback from such a change would be that it would make searching on regulator within bounds impossible; but that could be addressed by having a stored string in the database *as well as* the numeric value, only using the latter for such a search, not for display.

The same arises for EC/NF where I am less confident in the precision of the special value specifically which is computed by Magma.  The other numerical (real) values are computed by Sage (in some cases using libpari), then stored into text files (as decimal strings obviously) before upload.

We should probably open a new issue about this sort of question across the LMFDB.

**Comment by edgarcosta** [comment] 2022-01-22 14:00
For what is worth, one should think of the numeric data type as a string, as the string inputted is exactly the string outputed.

**Comment by bmatschke** [comment] 2022-01-22 16:38
Using Pari for the special L-values is possibly also not numerically stable, see "Important Caveat" on page 516 of their [user guide](https://pari.math.u-bordeaux.fr/pub/pari/manuals/2.13.3/users.pdf).

Yes, a new issue would be good. It would be very useful if the user can find out which numbers are provably known up to which precision, and for which ones there are no error bounds available.

**Comment by JohnCremona** [comment] 2023-01-05 14:33
I am going to open a new issue for the similar bug/feature for elliptic curves over number fields, where the relevant quantities are: height(s), regulator, period(s), L-value.  These have not all been computed to the same precision so there is no quick fix.  More recent data has been computed 20 128-bit precision but some older data is at lower precision (e.g. 53 bits).  Probably the best thing to do would be to recompute these quantities to 128-bit precision for all the curves, but that will take a while.

**Closed by JohnCremona** 2023-01-05 14:33 UTC
Labels: ECQ
