### ISSUE TITLE
Modular curve pages broken on blue

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5260] opened 2022-11-11 14:44 UTC
From the feedback page:

https://blue.lmfdb.xyz/ModularCurve/Q/24.24.1.2/
https://blue.lmfdb.xyz/ModularCurve/Q/?hst=List&level=24&index=48&genus=2&search_type=List

are broken

**Comment by AndrewVSutherland** [comment] 2022-11-11 15:12
@jwj61 In general, I agree with you, however I appreciate you posting this as we are actively working toward moving modular curves to beta in the next month and this bug report is helpful.  I just pushed a quick fix to the problem, which is caused by in-progress work on showing lattice diagrams that doesn't handle cases where we don't have precomputed lattice data. I expect @roed314 can take a look at this on Monday and make a better fix, but its helpful to others to have the pages working in the meantime.

Perhaps going forward we should think about creating an alpha.lmfdb.xyz to host branches that are not yet ready for beta but for which we might appreciate bug reports.

Both the links you posted now work, so I'm closing this issue.

**Closed by AndrewVSutherland** 2022-11-11 15:12 UTC
Labels: Modular curves
