### ISSUE TITLE
degree 3 L-functions

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#499] opened 2015-10-28 17:39 UTC
On the page http://beta.lmfdb.org/L/degree3/ the link "list of degree 3" L-functions takes you to the first zeros page. This page seems to be all about browsing. There doesn't seem to be searching capabilities
for Maass forms of degree 3 or for symmetric square L-functions. There is a nice search capability for dimension 3 Artin L-functions.

**Comment by davidfarmer** [comment] 2016-05-02 11:26
Duplicate of #1072

**Closed by davidfarmer** 2016-05-02 11:26 UTC
Labels: Lfcns
